### ISSUE TITLE
S3 [Task] Resolve Lint Errors

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#101]
Added to Sprint 2 (milestone) during 9/17/18 Sprint planning meeting.
Uses Pep 8 standards
Pylint runs the tool.

Issue | Resolve Lint Errors
----------|----------
T-shirt size: S(mall), M(edium), L(arge) | M
Story Points - Fibonacci (1,2,3,5,8,13) | 5

**Comment by jbobo** [comment]
wrote a script to run py-lint recursively on all python files, so I have a list of files with issues, and the warnings/convention/errors that were found. I'll look at the errors and talk to Satish about whether an auto formatter like AutoPEP8 would be worth using. 

One question: Do we care about warnings and conventions, or only errors?

for example: a warning would be that you have an unused argument, a convention would be a missing docstring, and an error would be an import error or anything else causing runtime errors.

**Comment by jbobo** [comment]
I'm mostly seeing a lot of import errors. I've noticed that we have a lot of empty _init_.py files in subdirectories, but can't seem to find a _init_.py file for the whole package in the root project directory. Do we consider the whole project to be one python package, with all of our subdirectories as modules?

**Comment by jbobo** [comment]
I'm thinking a lot of these errors are because I'm running Pylint on the static codebase rather than running it in the container. I'll try that and see if it makes a difference.

**Comment by codingalyona** [comment]
3 points for sprint 3.

**Comment by codingalyona** [comment]
Ned worked on dependencies files; got feedback; will send a PR once done

**Comment by jbobo** [comment]
Regarding E1101: no-member
 
http://pylint-messages.wikidot.com/messages:e1101

>False positives: This message may report object members that are created dynamically, but exist at the time they are accessed.

looking at how to properly ignore these, it looks like some of our libraries may be dynamically generating some stuff, which is causing our linting errors both in pylint in in our IDEs. I'm going to ignore the rbac* and sawtooth* modules in pylint to get around this, which seems to be the recommended solution.

**Comment by jbobo** [comment]
Regarding E0401: import-error

a number of these errors are due to Protobuf imports and resolved after running `bin/build -p` 

So I'm gonna ignore *.protobuf and *.*.protobuf modules. After building we're getting more issues on the build protobuf files, so I'll ignore the built files completely. That should make it so that devs can run the linter, while allowing us to use it in travis.

**Comment by jbobo** [comment]
Regarding W0613: unused-argument

getting a number of these errors:

>W0613: Unused argument 'metadata' (unused-argument)

In all of the cases I've looked at these are false positives. So I'm going to ignore the issue in setup.cfg

**Comment by jbobo** [comment]
@agoldingay can we close this issue now?

**Comment by agoldingay** [comment]
closing
