### ISSUE TITLE
[User Story] Adopt development branch for CI/CD and code quality management

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#102]
Added to Sprint 2 (milestone) during 9/17/18 Sprint planning meeting. This is a task for All who contribute code.
This captures the entire CD/CD process. Relevant dependencies/issues are captured below. Moved off S2 plan.

**Comment by kthblmfld** [comment]
Marking this as blocked as we don't have a clear means of how we will perform the merge from develop to master. We will need config rights on the repo to determine merge options, more mature CI/CD build out in Travis, and consensus with the Sawtooth community about the decision to adopt GitFlow.

**Comment by kthblmfld** [comment]
Moving this back to the backlog since we are at least a few sprints away from having the infrastructure in place to implement the develop branch approach.

**Comment by adamgering** [comment]
Roll call, do any of the maintainers own this repo?

**Comment by adamgering** [comment]
If not, who does?

**Comment by nadiabahrami** [comment]
Old issue. replaced by #984
