### ISSUE TITLE
Change User Creation process

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#1044]
[User Story] [Epic] | Change User Creation process
----------|----------
T-shirt size: S(mall), M(edium), L(arge) | M
User Story | "As a developer I want all UUIDs to have the same format"

**Description:** Currently we use UUID4 for generating new packs and new groups.  We do not do the same for new users.   We need to change that to match the other UUIDs.  This will need to create a user object in the user mapping table even if they have no external providers.  In that scenario it will have an provider_id of None and a remote_id of None and only have an next_id.  and a public key stored on the user mapping table.  The main file to be affected is server/api/users > create_new_user function.

**Acceptance Criteria/Tests:** Users created through the app will use the UUID V4 and test that are associated with this feature.  User created into the user mapping table.  Can log in and function as a user currently does in the front end.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
