### ISSUE TITLE
Remove relationship_id field and usage

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#1045]
User Story | Remove relationship_id field and usage
----------|----------
User Story Title | Remove relationship_id and usage
T-shirt size:  | M

**User Story**  "As a developer we need a UUID schema that will be the same through out the app.

**Description** Currently UUIds are of a mixed format across the app and there is no way to have them be linked between AD providers.   The relationship field is an exact copy of the remote_id fields and is used as the main id for forming objects on ingestion.  This needs to be removed after being replaced by a next_id.  Move through the app and remove it and make sure it is replaced correctly by next_id.  Files affected will be providers/common/inbound_filters, leger_sync/inbound/listener.  And everywhere else remote_id is references.

**Acceptance Criteria/Tests**  Tests must be associated with this along with the changes to removal of relationship_id from the filters.  The result is that relationship_id should no longer exist in the app.

**Comment by Srinuthalapati** [comment]
![issue 1311 blocking - 1045 story](https://user-images.githubusercontent.com/23491817/54485447-f60ca080-4835-11e9-9320-7fb281e571cf.JPG)

**Comment by Srinuthalapati** [comment]
At present, the "relationship_id" field is used in - 

![relationship_id field usages](https://user-images.githubusercontent.com/23491817/54485707-bbf1cd80-483a-11e9-9a25-e4bd48d22e42.JPG)

**Comment by Srinuthalapati** [comment]
As mentioned in the description, "**relationship_id**" field/variable/parameter is **not used** in the files "providers/common/**inbound_filters**", "ledger_sync/inbound/**listener**".
