### ISSUE TITLE
Add provider_id to data schema

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#1049]
[User Story]  | Add provider_id to data schema on ingestion
----------|----------
T-shirt size: S(mall), M(edium), L(arge) | 3
User Story | [Value Statement] "As a developer I need to know where the data came from easily"
Description | Currently on ingestion we eliminate the provider ID from the data payloads.  We need to have the provider_Id added to the data payloads to be able to sync outbound 
Acceptance Criteria/Tests | Test to ensure the provider_id has been appended to data payloads on ingestion

**Comment by PatrickLammers** [comment]
added for George to get his feet wet...  but he's not yet in Git so I can't assign to him.
