### ISSUE TITLE
S2 Finish Data Persistence Investigation

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#105]
Added to Sprint 2 (milestone) during 9/17/18 Sprint planning meeting.

Issue |Finish Data Persistence Investigation
----------|----------
T-shirt size: S(mall), M(edium), L(arge) | M
Story Points - Fibonacci (1,2,3,5,8,13) | 5

**Comment by adamgering** [comment]
Docker data volumes work for development purposes. 
May need to revisit this issue for production configuration if not using docker data volumes.
Related bug with ledger_sync: #122 solved via PR #142
