### ISSUE TITLE
Switch user login to Email

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#1050]
[User Story] [Epic] | Change user login to email instead of username
----------|----------
T-shirt size: SML | M
User Story | "As a user I want an email login that is unique and I know easily"
Description | Currently we do not enforce uniqueness to login.  This is liable to cause duplicates of users and cause confusion within the system as to who they login as.  We need to enforce email uniqueness.  remove the ability to get username assignment on account creation and drop username as a means of logging in.  
Acceptance Criteria/Tests | Login happens with email and you can't login with a username or create one with a username.

**Comment by PatrickLammers** [comment]
we need a login that is unique and cannot live in all ?IDp.

**Comment by PatrickLammers** [comment]
This is part of the larger "reevaluate our login fields" effort in V2

**Comment by PatrickLammers** [comment]
apparently we decided not to do this...  app will continue to use Username.
