### ISSUE TITLE
Reverse the order of ledger sync processing

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#1053]
[User Story] [Epic] | Reverse the order of Ledger Sync Processing.
----------|----------
T-shirt size: S(mall), M(edium), L(arge) | M
User Story | "As a user I want ingestion to be fast."
Description | Initial/delta inbound sync -- Currently the ingestion cycle is the Block chain ingestion happens prior to the rethinkdb ingestion.  This slows it as the blockchain portion is the longer part of the two.  WE need to reverse the processing to do rethink first and then put it into blockchain.
Acceptance Criteria/Tests | Make sure the process is flipped

**Comment by PatrickLammers** [comment]
Per discussion with Chris, to ensure consistency we need to write to ledger first and then have the DB & UI reflect that "truth"
