### ISSUE TITLE
Remove the metadata fields in rethink objects

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#1054]
User Story | Remove metadata fields in rethink objects
----------|----------
T-shirt size: | S
User Story | "As a developer I do not want excess fields created by us to be maintained.  

**Description**  Right now we keep a metadata field on all objects.  With the metadata table we do not need this extra field.  It should be removed.  This process occurs in ledger_sync/inbound/listener  in the metadata creation step.  For an example of hat currently happens look at the groups and users table in rethinkdb and find the metadata field is empty.

**Acceptance Criteria/Tests** Remove the metadata field and have tests to back up the fact that it is not created.

**Comment by PatrickLammers** [comment]
some investigation needed...  Sawtooth is designed to be extensible via this metadata field.  Lets be sure we are *not* killing the meta data that we need.  Code comments say "meta data not stored on chain" -- let's make sure we are in sync with schema descriptions in "ledger object definitions" on the sharepoint.

**Comment by PatrickLammers** [comment]
Per conversation with Ned...  the orginal design calls for actually having this metadata field but it is currently not used correctly.  We will close this one and open a new ticket once we understand it better...
