### ISSUE TITLE
Refactor ledger_sync/inbound/listener.py

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#1055]
[User Story] [Epic] | Refactor Ledger_sync inbound listener.py
----------|----------
T-shirt size: S(mall), M(edium), L(arge) | S
User Story | "As a developer I do not want to have duplicate code in my product"
Description | Currently the listener for inbound ledger sync has duplicates in it's code.  This should be refactored
Acceptance Criteria/Tests | Cleaner non-duplicated code and tests associated with this.

**Comment by PatrickLammers** [comment]
Refactor this if we happen to be in this code to fix an issue....
