### ISSUE TITLE
Move config out of common

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#1059]
[User Story] Move config out of common folder
----------|----------
T-shirt size: S(mall), M(edium), L(arge) | M
User Story |"As a developer there should only be one config for the app."
Description | There is a separate config file for the app in the common folder.  Need to move that to the external config.  
Acceptance Criteria/Tests | One config

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
