### ISSUE TITLE
S3 [User Story] Increase Python Tests

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#106]
Added to Sprint 2 (milestone) during 9/17/18 Sprint planning meeting. Assigned to dev9 team.

Issue |Increase Python Unit Tests
----------|----------
T-shirt size: S(mall), M(edium), L(arge) | L
Story Points - Fibonacci (1,2,3,5,8,13) | 8

**Comment by adamgering** [comment]
Working on it now

**Comment by kthblmfld** [comment]
I have a branch out with details in the commit message. Quick summary: Extracted out reusable parts, changed test loader to load all tests in the directory, renamed dir per best practices... PR coming soon.

**Comment by codingalyona** [comment]
review the user story and decompose around the feature. the unit testing will be a part of user stories. 8 story points. (add 2 tasks: unit and integration tasks).

**Comment by adamgering** [comment]
Closing, as there is no completion criteria for this story.
