### ISSUE TITLE
[Task] Change logging level to INFO globally

### ISSUE THREAD

**Issue by mtn217** [hyperledger/sawtooth-next-directory#1064]
[User Story] [Epic] | Change logging level to INFO globally
----------|----------
User Story Title | Change logging level to INFO globally
T-shirt size: S(mall), M(edium), L(arge) | M
User Story | [Value Statement] "As a user of a certain type (specify), I want to do something (action) so I can provide business value"
Description | Logging is not standardized throughout the various containers. Change the logging level to INFO globally.
Acceptance Criteria/Tests | The list of tests or criteria to be used to validate the story has been completed. May still need UAT or SIT / integration testing with other stories.

**Comment by jbobo** [comment]
Related to #1068 

The solution to #1068 also closes this ticket.
