### ISSUE TITLE
S2 Merge in Test Data Loader 

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#107]
Added to Sprint 2 (milestone) during 9/17/18 Sprint planning meeting.

Issue |Merge in Test Data Loader
----------|----------
T-shirt size: S(mall), M(edium), L(arge) | M
Story Points - Fibonacci (1,2,3,5,8,13) | 5

**Comment by kthblmfld** [comment]
Looks like this is the 3rd item for this unit of work. Will move it to Done once I get that second approval . :)
