### ISSUE TITLE
[BLOCKED] Add members to role/pack at creation time

### ISSUE THREAD

**Issue by PatrickLammers** [hyperledger/sawtooth-next-directory#1075]
User Story | Add members at role/pack creation time
----------|----------
T-shirt size:  |  M
User Story | "As a role/pack creator, I probably have a few people in mind when creating a new role/pack.  I should be allowed to search for them by name and add them at creation time.  This would save me from having to notify them of the role/pack existance and then they request membership and I then must approve.  Removing steps speeds process and saves money."
Description | This is A16 on the V5 version of the XD UI mockups. 
Acceptance Criteria/Tests | Demonstrate that we have an additional step now in role/pack creation where I can add members directly.  Demonstrate that this is optional.  Show that search functionality allows me to easily find a person by name, username, email. [search not available until #847 is working?]
Questions | Should this trigger a notification to the user who just got added to a role without asking?  Would we be able to send one notification summarizing all the roles in the case of a pack?  If I can't remember a person's name but I know their manager, can I switch from this page to the people page to look them up w/o losing my work?

**Comment by PatrickLammers** [comment]
size estimate reflects the thinking that search ability is a separate story (#847) This story is just about building the page for adding members at creation time.  Since adding members is optional, the functionalty of creating roles/packs isn't impacted.

**Comment by pgobin** [comment]
Discussion of intended behavior needed.

**Comment by PatrickLammers** [comment]
need to get some workflow questions answered before tackling this one...

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
