### ISSUE TITLE
Ledger Sync to Outbound Queue

### ISSUE THREAD

**Issue by mtn217** [hyperledger/sawtooth-next-directory#1077]
[User Story] | Investigate LDAP Outbound Sync
----------|----------
User Story Title | Investigate and fix LDAP Outbound Sync
T-shirt size: S(mall), M(edium), L(arge) | M
User Story | 
Description | Currently, changes that are being made to LDAP groups/users on NEXT are not being applied to LDAP provider even though the inbound LDAP ingestion has been working. Figure out the current state of the LDAP outbound sync and properly implement the outbound LDAP sync to allow changes on NEXT be applied to the LDAP provider.
Acceptance Criteria/Tests | 1) Write up for current state of LDAP outbound sync answering "Why is LDAP Outbound Sync not working?" 2) UML diagrams for present state and desired future state.  3) demo that changes made in Next are correctly written back to AD (all CRUD cases)

**Comment by PatrickLammers** [comment]
UML for current state and proposed state?

**Comment by PatrickLammers** [comment]
George gets to work on this one too

**Comment by PatrickLammers** [comment]
put back the "and fix" language instead of having #1249... no sense in tracking two separate tickets in the same sprint for the same issue

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
