### ISSUE TITLE
[UI Design] App config settings page

### ISSUE THREAD

**Issue by PatrickLammers** [hyperledger/sawtooth-next-directory#1088]
User Story | We need a page where a SysAdmin can configure the global app settings
----------|----------
T-shirt size: | 
User Story | "As a SysAdmin of the NExt app, I want to see a UI page that only SysAdmins can get to that allow me to set the app config settings."
Description | related to #70 
Acceptance Criteria/Tests | The page should only be accessible to the System Administrator account.  Page should have a consistent look and feel along with the rest of the app.  When user presses 'Save' the settings should take effect without the need to restart the app.  The data entered here shall be preserved across deployments and should be backed up for disaster recovery.

Data includes but is not limited to:

- whether to require LDAP credentials for login or allow stand-alone NEXT app creds
- which LDAP server(s) we are connecting to
- email servers & settings we are using
- blockchain servers to connect to?  settings?
- TTL for proposals
- global default time for role access expiration (in future this may be a 'per role' setting)
- lead time for alerting on role expiration
- global setting for whether or not to allow delegation (#64)
- global setting for whether or not to allow escalation (hierarchical) (#64)
- how many levels to allow escalation
- rules for multi-party approval (all owners, just one owner, at least half of owners)
- The alert-lead time on access expiration should be less than the access duration time 

Of course, the above list is just a starting point for discussion with PO and team.  What other settings are buried in the code?

**Comment by pgobin** [comment]
Good candidate for a design issue.

**Comment by PatrickLammers** [comment]
per discussion with PO, this is a complicated concept with network configs.  We will live with these settings in .env for now.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
