### ISSUE TITLE
Logout on refresh

### ISSUE THREAD

**Issue by PatrickLammers** [hyperledger/sawtooth-next-directory#1093]
Bug | refreshing the page in the browser takes me to login screen.
----------|----------
Expected behavior | refreshing the page should refresh the page -- ideally show new content.
Actual behavior | logs me out and takes me back to login screen.
Repro steps | from anywhere within the app press refresh button on the browser.
Build | How do I see the version number again?
Severity | 1. crash/unable to recover
Details/Notes | makes us look dumb.

**Comment by PatrickLammers** [comment]
Seems to be tied to cookies and the t-mobile.com domain.  Hitting this site via the IP address lets me refresh as much as I want...  but hitting this same site via the domain name it looks like not all cookies are getting set.

**Comment by PatrickLammers** [comment]
related to #1108 ??

**Comment by PatrickLammers** [comment]
let's let Ned focus on inbound and outbound in S12

**Comment by satkeeva** [comment]
Reassigning to Ned since he fixed it on 02/07/2019
