### ISSUE TITLE
[Bug] Role members display as 'Unavailable'

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#1100]
Bug | Role members display as 'Unavailable'
----------|----------
Expected behavior | Role members should not display as 'Unavailable'
Actual behavior | What it really did instead...
Repro steps | Detailed instructions so anyone can see the error.
Build | which build number exhibits the issue?
Severity | _1. crash/unable to recover 2. blocks functionality 3. clunky but functional 4. Nit or minor UI issue_
Details/Notes | Any more observations...

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
