### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by PatrickLammers** [hyperledger/sawtooth-next-directory#1111]
User Story | We have too many roles/packs/people -- help me find what I want
----------|----------
T-shirt size:  |  L
User Story | "As a user of NeXt browsing all available people & roles/packs is overwhelming, we should limit the results via search so I can find what I want."
Description | enter a keyword to search by and I will see results where this term is in searched fields (below).
Acceptance Criteria/Tests |  Results should display as I type them...  the page will refresh and narrow down results in (near) real time.  It's OK if my search term is contained in a field that is not immediately visible in the results (ie if tiles dont show description, I still want to see that tile in the result set)   This first attempt at search will NOT include AND, OR NOT in the search functionality.  The main variations on Search are detailed below.

Requirements:
*Needs to be done, tested and available on the DEMO endpoint by morning of 2/14/19*
 
Backend REST API -- immediately set up to return mock data (or did we land on coding to an API??), will return actual data by 2/13
 
Real time results vs search button 
-- if we do 'search as you type' we need to also pass in the sort order we would like the results to be in…  sorting on the backend is preferred to sorting in the UI.  Results should be limited the result type (ie "browse" page search is limited to roles/packs as results)
 
Three main areas to enable search:
1.	Browse screen
a.	Search role/pack names - returns any role containing this string
b.	Search owner name
c.	Search owner email
d.	Search description text
2.	People screen 
a.	Search name
b.	Email,
c.	Job Title (Job title not returned by API yet -- later sprint)
d.	Manager name
e.	Manager email
3.	Broad search 
a.	Broad search (left hand pane) -- needs a new page for displaying results broken out by type of result.
i.	Roles/Packs -- title and description and owner email, owner name
ii.	People -- name and email and manager
iii.	People -- where we matched the person's manager -- implies we search the manager name in the org
 
The idea here is that this page would display any result type divided up by result type.  Ie enter "chrisspanto" and you see all packs and roles owned by Chris, the person object that *is* Chris and all the person objects that are Chris's direct reports.  All displayed in beautiful UI making it easy to find what I want.

**Comment by pgobin** [comment]
We need to discuss architecture before proceeding.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
