### ISSUE TITLE
Logical display of Packs & Roles

### ISSUE THREAD

**Issue by PatrickLammers** [hyperledger/sawtooth-next-directory#1112]
User Story | We should strive to make it very clear what packs and roles I am a member of...
----------|----------
T-shirt size: | 
User Story | "As a user of nExT, I want to be able to see all roles and all pack in the left pane of the UI so I can quickly and reliably see my current state."
Description | This is a change of how we display a user's memberships.  We currently have one heading called "your roles/packs"   Lets make these into two separate lists -- "your roles" and "your packs"   Roles get added to the list when an owner approves membership.  Packs get added to the list once all roles in the pack have been approved.  The two lists *will* show duplicate information because the pack I have does contain all of the roles I have.  "your requests" will continue to show any items with a Pending status -- once all role requests in a pack are approved, the pack will move from 'your requests" to "your packs"
Acceptance Criteria/Tests |  the roles and pack names will show under the headings as described above.

**Comment by pgobin** [comment]
@PatrickLammers Can this be converted into a design issue? The ask is clear, but I believe UX has ideas of morphing this into it's own screen that includes and expired role view, etc.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
