### ISSUE TITLE
[UI Design] Requester message to approver flow + interaction

### ISSUE THREAD

**Issue by PatrickLammers** [hyperledger/sawtooth-next-directory#1113]
User Story | Requester message to approver flow + interaction
-----------|----------
T-shirt size: S(mall), M(edium), L(arge) | S
User Story | "As a user of a NeXt, you ask me for a message to send to the owner of the role/pack but this message doesn't seem to show anywhere on the approval workflow."
Description | 
Acceptance Criteria/Tests | The message should be visible to the approver to help them decide...  The message should remain in the history and be written to the ledger.    Maybe remain visible in the request UI for reference (?)

**Comment by pgobin** [comment]
Needs additional specs from UX. Mockups and flows don't fully detail expected functionality.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
