### ISSUE TITLE
Abstract DB connection usage into a connection pool

### ISSUE THREAD

**Issue by jbobo** [hyperledger/sawtooth-next-directory#1116]
Epic | Abstract DB connection usage into a connection pool
----------|----------
Epic Title | Abstract DB connection usage into a connection pool
T-shirt size default is Extra Large | XL
Description | The approach used to query RethinkDB by NEXT microservices must be standardized and consistent. 
Business Need (the why): | The inconsistencies have been causing side effects and instability.
Details | Some microservices use REPL which is not recommended for prod in rethink docs. Some microservices also pass a global connection object around which risks unexpected closure by rethink. we need to ensure that any microservices that query rethink are using a standardized process or connection pool to prevent connections from expiring or having too many connections opened at once. see: [here](https://github.com/lucidfrontier45/RethinkPool) and [here](https://github.com/njouanin/repool).
User Scenarios | TBD
Acceptance Criteria/Tests | All current unit and integration tests should still pass. Data flow should be unchanged.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
