### ISSUE TITLE
Inbound sync from AD doesn't handle removals

### ISSUE THREAD

**Issue by PatrickLammers** [hyperledger/sawtooth-next-directory#1122]
Bug | Inbound doesn't work for removed items
----------|----------
Expected behavior | If a user is removed from a role in AD, we should reflect this in Rethink and ledger 
Actual behavior | inbound sync seems to drop these...
Repro steps | Add a user to a role in AD (via direct AD -- not Next)...  wait for NExt to pick up this change and reflect it in the UI.  Now remove that user from that role via direct AD.  Wait for Next to pick it up... keep waiting.  
Build | no idea... see #822
Severity | 2. blocks functionality
Details/Notes | lets be sure we have automated tests on inbound sync to demo this.

- [ ] Create/update plantuml data-flow diagrams for inbound delta sync.
- [ ] Submit plantuml diagrams for documentation
- [x] Setup small test LDAP instance to generate payloads for group member removal.
- [x] Collect debug logs to confirm/update data-flow for inbound delta sync group member removals.
- [x] Determine viable bug fix.
- [x] Implement bug fix.
- [ ] Determine integration testing method to confirm the fix and prevent recurrence of the bug.
- [ ] Implement and commit tests.

**Comment by PatrickLammers** [comment]
Seems like a bug on the functionality we added in #334

**Comment by nadiabahrami** [comment]
Hey there the UML is kind of confusing.  Can we get function to function mapping or module to module mapping?

**Comment by jbobo** [comment]
yup, I'll rewrite them to be more specific after I submit the integration tests for the bugfix

**Comment by PatrickLammers** [comment]
seems like we need an update to UML docs
