### ISSUE TITLE
[Task] Create global connection pool module.

### ISSUE THREAD

**Issue by jbobo** [hyperledger/sawtooth-next-directory#1124]
Task | Create global connection pool module.
----------|----------
Task Title | Create global connection pool module.
Description | Create a global connection pool module to use by microservices that connect to rethinkDB. This is not implementation, only the creation of the module to be used by microservices being affected by #1116. see: [here](https://github.com/lucidfrontier45/RethinkPool) and [here](https://github.com/njouanin/repool).
Business Need (the why): | We should be using a global connection pool to ensure that we never have too many concurrent connection open at once.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
