### ISSUE TITLE
[User Story] Use connection pool in rbac-providers

### ISSUE THREAD

**Issue by jbobo** [hyperledger/sawtooth-next-directory#1125]
[User Story] | Use connection pool in rbac-providers
----------|----------
Epic Title | #1116 
User Story Title | Use connection pool in rbac-providers
T-shirt size: S(mall), M(edium), L(arge) | M
User Story | Not using a connection pool causes instability in rbac-provider services.
Description | Use the global connection pool module from #1124 to get, reconnect, close, and release rethinkDB connection objects within rbac-provider module functions. 
Business Need | Opening and closing multiple connections without the use of a connection pool risks leaving open connections hanging or having too many connections open at once. 
Acceptance Criteria/Tests | Data flow will remain unchanged and all existent unit/integration tests should pass. The connection pool is used by all functions in `rbac/provider/*` modules to connect to rethinkDB
Depends On | #1124

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
