### ISSUE TITLE
Look into and verify correct usage of index_create() for rethinkdb

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#1128]
[User Story]| Look into and verify correct usage of index_create() for rethinkdb
----------|----------
T-shirt size: S(mall), M(edium), L(arge) | S
User Story | "As a dev I want my Database queries to be fast and efficient."
Description | Currently we are using multiple secondary indexes on tabes in rethink.  It may not be done correctly as there are different parameters that should be in each declaration.  We need to research and confirm that theway it is written is correct for our use cases.    https://www.rethinkdb.com/api/python/index_create/
Acceptance Criteria/Tests | Either a comment closing this ticket syaing it's done correctly after researching.  Or a PR with the correct formatting for index creation and queries.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
