### ISSUE TITLE
[Bug] Optimize user query performance

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#1129]
Bug | Optimize user query performance
----------|----------
Expected behavior | Query to get either single user or all users, `fetch_user_resource` and `fetch_all_user_resources`, respectively, can take seconds to retrieve data. Investigate and correct whatever the bottleneck is.
Actual behavior | What it really did instead...
Repro steps | Detailed instructions so anyone can see the error.
Build | which build number exhibits the issue?
Severity | 3
Details/Notes | Any more observations...

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
