### ISSUE TITLE
Build/Prop on a schedule

### ISSUE THREAD

**Issue by PatrickLammers** [hyperledger/sawtooth-next-directory#1154]
User Story | Regular builds propped to TEST
----------|----------
T-shirt size: SML | S
User Story | We should be able to have the latest build of NEXt available on the TEST env every day so that we can see changes as they roll in and provide early feedback
Description | I think a cron job was mentioned in the discussion...
Acceptance Criteria/Tests |  TEST env has a stable build.  Tests passed.  Test data is available tool.  Push happens during low activity time of the day but should happen at same time every day.  We should make it clear to everyone how to tell if the daily drop succeeded (do I check travis?  see a version on the UI?  build log?).

**Comment by jbobo** [comment]
Just finished. Set a cron job on the demo server to pull new source and redeploy every Tuesday at 6am.  The stg server pulls latest source and redeploys every day at 6am.

**Comment by jbobo** [comment]
as per our discussion yesterday I removed the cron job on the demo server. Demo will have manual deployments at the end of each sprint until CI/CD is implemented and the stg server will have deployments every morning at 6am with a cron job. Added logging on each server to track deployment times.
