### ISSUE TITLE
[Bug] Limit number of peers returned

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#1233]
Bug | Limit number of peers returned
----------|----------
Expected behavior | Relationship queries should limit number of peers returned.
Actual behavior | For large organizations, thousands of peers can be returned in one response object.
Repro steps | Detailed instructions so anyone can see the error.
Build | which build number exhibits the issue?
Severity | 3
Details/Notes | Any more observations...

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
