### ISSUE TITLE
[Task] Set develop branch as default

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#124]
Task | Set develop branch as default
----------|----------
Task Title | Set develop branch as default
User Story | #102 
Epic |
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 1
Description | Set development branch as default
Business Need (the why): | suggested git strategy by Satish
Dependencies | #125
Assumptions | Complies with evolving Sawtooth governance with regards to repo policies

**Comment by adamgering** [comment]
Blocked by #125

**Comment by nadiabahrami** [comment]
Old issue.  Replaced by #984
