### ISSUE TITLE
Drop and recreate develop branch

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#126]
Task | Recreate develop repo
----------|----------
Task Title | Recreate develop repo
User Story | #102 
Epic | link associated Epic, if applicable
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 1
Description | Drop and recreate develop branch
Business Need (the why): | Suggested we move PRs to develop branch
Applications or Systems impacted | 
Dependencies | #124 #125 #127 #119 
Assumptions | Use of develop branch complies with evolving Sawtooth governance repo policies and new maintainers decision

**Comment by adamgering** [comment]
Don't re-create the develop branch until we are ready to switch PRs to that branch, able to set it as default branch (#124) and configure appropriate branch permissions.

**Comment by PatrickLammers** [comment]
same as #984 ??

**Comment by nadiabahrami** [comment]
Old issue.  Replaced by #984
