### ISSUE TITLE
S2+ [Task] Establish repo maintainers

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#127]
Task | Establish repo maintainers
----------|----------
Task Title | Establish repo maintainers
User Story | #102 
Epic | 
T-shirt size default is S(mall) | M
Story Points - Fibonacci (1,2,3,5) | 3
Description | Establish repo maintainers
Business Need (the why): | Sawtooth Governance
Applications or Systems impacted | Github repo
Dependencies |
Assumptions | Project will be a subteam of Sawtooth

**Comment by mtn217** [comment]
Adam and Keith would like to be added to the MAINTAINERS.md, further discussion is needed on what it means to be a maintainer (i.e. daily code reviews).

**Comment by agoldingay** [comment]
closing issue. Adding Adam to be "maintainer" is being addressed with #199. If adding Keith is addressed, a new issue will be created.
