### ISSUE TITLE
Advanced Search Packs

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#1272]
User Story | Search Packs
----------|----------
Epic Title | #1111 Search
T-shirt size: SML | 
User Story | As a Next, I should be able to search for packs, and get back the roles  that match the  role owner fields
Description | Search for owners rapidly to get roles displayed.  This may require modification of the JSON and consideration on sorting or display in the front end. 
Acceptance criteria | able to issue a search request and get back a correct search response for packs.  Used in the Browse page, in building a pack and in delegation pages.  Tests and Updated swagger associated

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
