### ISSUE TITLE
Advance User Search

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#1273]
User Story | Search Users
----------|----------
Epic Title | #1111 Search
T-shirt size: SML | 
User Story | As a Next, I should be able to search for users, and get back the roles  that match the  user's manager fields
Description | Search for managers rapidly to get users displayed.  This may require modification of the JSON and consideration on sooting or display in the front end. 
Acceptance criteria | able to issue a search request and get back a correct search response for users.  Used in the Browse page.  Tests and Updated swagger associated

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
