### ISSUE TITLE
Set master branch permissions

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#128]
Task | Set master branch permissions
----------|----------
Task Title | Set master branch permissions
User Story | #102 
Epic | 
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 1
Description | Master branch permissions should only allow merges by maintainers.
Business Need (the why): | Code quality and CI/CD process
Applications or Systems impacted | Github, CI/CD
Dependencies | #127 #125 #119 
Assumptions |

**Comment by nadiabahrami** [comment]
Old issue.  Replaced by #984
