### ISSUE TITLE
[Bug] Chatbot - icon not loading properly after request submission

### ISSUE THREAD

**Issue by mtn217** [hyperledger/sawtooth-next-directory#1291]
Bug | Chatbot - icon not loading properly after request submission
----------|----------
Expected behavior | After submitting a request, I should see an icon in the chat bot that accompanies the confirmation the chatbot gives me. 
Actual behavior | The confirmation gets sent with a box outlined in black. See attached photo . 
Repro steps | 1) Visit any role and request access. 2) Click yes please and then fill out the reasoning for the request. Now the confirmation should come up by the chat bot and the box should appear. 
Build | 0.6.9
Severity |  4. Nit or minor UI issue_
Details/Notes |

![buggeroo](https://user-images.githubusercontent.com/14936566/53205081-20c25b00-35e2-11e9-820b-6a31cbe5c446.PNG)

**Comment by Akashkotian7** [comment]
working fine even in windows

![2019-03-25.png](https://images.zenhubusercontent.com/5be91a64e8e9d45fbb5b69c7/0dbcff28-e6fb-4ddc-a55a-0dcbb189d4ab)

**Comment by PatrickLammers** [comment]
Not repro
