### ISSUE TITLE
[Bug] Chatbot doesn't know user is already a role member

### ISSUE THREAD

**Issue by mtn217** [hyperledger/sawtooth-next-directory#1293]
Bug | Chatbot doesn't know user is already a role member
----------|----------
Expected behavior | Chatbot should know that I am already a member of a role and not ask me if I would like to request access to a role I already am a member of.
Actual behavior | Chatbot asked if I wanted to request access to a role I am a member of already.
Repro steps | 1) Join a role as a role member 2) Visit the particular role's page 
Build | 0.6.9
Severity | 3. clunky but functional
Details/Notes | Any more observations...

![chatbot-bug](https://user-images.githubusercontent.com/14936566/53272729-f090c000-36a6-11e9-9c36-f43f0e9e054d.PNG)
(I'm currently authenticated as user Jackie Chan)

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
