### ISSUE TITLE
Set develop -> master branch sync process

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#130]
Task | Set develop -> master branch sync process
----------|----------
Task Title | Set develop -> master branch sync process
User Story | #102 
Epic | link associated Epic, if applicable
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 2
Description | There should be a defined process whereby develop branch passes CI/CD testing
and via a manual or automated process involving maintainers, master gets synced with develop.
Business Need (the why): | master will represent stable for secondary CI/CD
Applications or Systems impacted | Github repo and CI/CD
Dependencies | #125, #126, #127, #128, #129
Assumptions | Develop branch complies with evolving sawtooth governance and repo standards.

**Comment by nadiabahrami** [comment]
Old issue.  Replaced by #984
