### ISSUE TITLE
UI Refactor

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#1307]
User Story | UI Refactor
----------|----------
User Story Title | UI Refactor
T-shirt size: S(mall), M(edium), L(arge) | S
User Story | As a user, I benefit from an agile team that sustains its velocity.
Description | Refactor minor areas where technical debt has accrued.
Acceptance Criteria/Tests | The list of tests or criteria to be used to validate the story has been completed. May still need UAT or SIT / integration testing with other stories.

**Comment by PatrickLammers** [comment]
not specific enough to be actionable....  we should specify areas that need the work so we can size it.
