### ISSUE TITLE
Create user_mapping table

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#1309]
[User Story] [Epic] | Create user_mapping table
----------|----------
T-shirt size: S(mall), M(edium), L(arge) | S
User Story | "As a developer I want all UUIDs to have the same format in the app"
Description | Create a table for the basis of the implementation of this epic of uniting UUIDs.  There should be one table with the following schema:

```
{ next_id: <string -  UUID4 internally generated>,
  provider_id: <string - provider_id>,
  public_key: <string - key created on signing>,
  remote_id: < string - Upstream GUID or UUID>,
  active: <boolean> 
}
```

**Acceptance Criteria/Tests** 
- Table is generated on app launch

**Comment by akgunkel** [comment]
This seems to just require adding the following to ./bin/setup_db: 
    LOGGER.info('Creating table: user_mapping')
    r.db(name).table_create('user_mapping', primary_key='remote_id').run(conn)
    r.db(name).table('user_mapping').index_create('next_id').run(conn)

Possibly without the primary key specified?
