### ISSUE TITLE
Next_ID implementation

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#1311]
[User Story] | Next_ID implementation 
----------|----------
T-shirt size: S(mall), M(edium), L(arge) | M
User Story | "As a developer I want all UUIDs to have the same format in the app"
Description | Create a next_id in UUID4 format and add it into the blockchain in ledger sync. Once confirmation has been made from the blockchain add an object with the following format to the user_mapping table during the ledger_sync steps.

```
{ next_id: <string -  UUID4 internally generated>,
  provider_id: <string - provider_id>,
  public_key: <string - key created on signing>,
  remote_id: < string - Upstream GUID or UUID>,
  active: <boolean> 
}
```
The main file to be worked in is ledger_sync/inbound/listener > process function

**Acceptance Criteria/Tests**
- Tests to cover next_id
- All next_ids for group objects, or users are in the same format whether they are created in Next or imported from one of our two providers.  
- All ids going to the front end are the next_ids
- Front end still works for search and UUIDs are created.
- All users and roles have a public key that is recorded with it

- [x]  switch uuids to conform on inbound
- [x] fix authorization with new uuids
- [x] fix manager calls with new uuids
- [x] add distinguished names to the user_payloads and into the blockchain
- [ ] Use next_id in the block chain entry
- [ ] add inbound entries into the user_mapping_table on entry
- [ ] switch out the user_id in the users table with next_id
- [ ] local_id for new user creation
- [ ] switch out user_id across the app with next_id
- [ ] correct authorization steps
- [ ] correct manager steps
- [ ] fix all tests
- [ ] manually test entire app
- [ ] write tests for anything malfunctioning silently

**Comment by PatrickLammers** [comment]
Migrated to new tmobile/sawtooth-next-directory repo
