### ISSUE TITLE
UUID uniformity

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#1312]
Epic | UUID uniformity through the app
----------|----------
T-shirt size default is Extra Large | XL
Description | Currently our app uses various formats across the app that is causing several issues.  (Not being able to map accounts, unknown ID use and display-ability by the UI, account logging issues, 'super-user' access to any account, lookup for outbound) . These need to be corrected via a good bas of one consistently used id throughout the app.
Business Need (the why): | This is the basis of how the app works
Stakeholders | Everyone

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
