### ISSUE TITLE
[Bug] Swagger API documentation is missing information

### ISSUE THREAD

**Issue by mtn217** [hyperledger/sawtooth-next-directory#1321]
Bug | Swagger API documentation is missing information
----------|----------
Expected behavior | When I view Swagger documentation, I should see all the information filled out for each API endpoint. 
Actual behavior | When I view Swagger documentation, most of the API endpoints are missing definitions. 
Repro steps | Follow the Sphinx docs Swagger setup page to view the latest version of Swagger locally. When viewing the Swagger documentation, the API endpoints will have missing information. 
Build | 0.6.9
Severity | 2. blocks functionality 
Details/Notes | Any more observations...

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
