### ISSUE TITLE
Blockchain response handling

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#1325]
[User Story] | Blockchain response handling
----------|----------
T-shirt size: S(mall), M(edium), L(arge) | M
User Story | "As a developer I want to handle all responses from the blockchain not just the rejected and approved responses."
Description | Currently the responses that are coming off the blockchain are not all handled.  The only responses being handled are REJECTED and APPROVED.  There was a response that stopped all imports in the queue caused by a different status and needs to be handled appropriately. The ticket includes looking up possible responses from blockchain api and handling them appropriately so that there are no stalls in loading.   This same handling will also need to be used in any proposal creation or any server api endpoints that do direct interaction to the blockchain.  (users)
Acceptance Criteria/Tests | Tests for handling other status.  Documentation on the statuses and how NEXT handles them(logs, retries, etc...)

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
