### ISSUE TITLE
[User Story] Validate Email Addresses on Signup

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#133]
|||
----------|----------
Bug Title | Email does not validate
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 2
Description | User email has no validation whatsoever.
Business Need (the why): | A valid email address is fundamental to verifying the identity of the user in the system
Applications or Systems impacted | Data integrity in the database, usability of the application

**Comment by PatrickLammers** [comment]
@kthblmfld What sort of email validation can we really do here?  
- Are we going to block usage of the app until the new user receives an email from neXt and verifies that he has access to it -- then let the registration complete?
- Are we simply going to verify the correct format of an email address "name@domain.com" ?
- would it be desirable to restrict the domain that can be used (like only "foo@t-mobile.com" can be used.  More secure this way?  App-wide config setting maybe?

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
