### ISSUE TITLE
Research -- on_behalf_of functionality

### ISSUE THREAD

**Issue by PatrickLammers** [hyperledger/sawtooth-next-directory#1341]
**Research:** Design the 'on_behalf_of' functionality to act on proposals
T-shirt size: S(mall), M(edium), L(arge):  M

**Description:**
Design the functionality around being able to act on a proposal on someone's behalf (to support DELEGATION and HIERARCHICAL approval features).  

**Requirements:**
1. actions taken on a proposal are correctly recorded to ledger when delegate/manager acts on them.
2. we don't record proposals that have expired during a delegation -- only those acted upon.
3.  UI will need to be able to reflect this information to user -- When Manager accepts on behalf of Approver, the UI can show this info in both the Manager's history and the Approver's history.
4. only needs to support ONE actor -- one person will be recorded as accepting or rejecting a proposal. However, anyone in the management chain can be the actor.  (see #1215 for hierarchical rules)  

**Acceptance Criteria**
- timeboxed work -- to be delivered in the first third of the sprint.
- Design review completed -- team understands and agrees on the design.
- work with the SM/PO to add the identified stories to the backlog.

Tasks

- [x] Research current state of on_behalf_of

- [x] Design a solution to include on_behalf_of within proposals and how it interacts with our APIs + UI, with PlantUML diagrams

- [x] Present ideas to team and receive feedback

- [x] Finalize solution and create a ticket to implement on_behalf_of

**Comment by mtn217** [comment]
Final solution has been noted in ticket #1357.
