### ISSUE TITLE
[Bug] Role owner keeps loading if they were not imported into users table

### ISSUE THREAD

**Issue by mtn217** [hyperledger/sawtooth-next-directory#1350]
Bug | Role owner keeps loading if they were not imported into Users table

**Expected behavior**
The role should display the owner and the role members when I navigate to the role page. 
**Actual behavior** 
When I navigated to the role "r_aem_users_admin" NEXT tries to look for the summary of the owner, svc_adds_unowned. But because svc accounts were not imported into NEXT, NEXT could not find the role owner for r_aem_users_admin. When I visit the page, it continually shows a loading animation for the owner and a loading animation for the chatbot. I have attached screenshots of the bug below.
**Repro steps** 
 1) Log in to NEXT. 2) Go to browse and enter the r_aem_users_admin role. 
Build | which build number exhibits the issue?
Severity | 3. clunky but functional
Details/Notes | NEXT calls the endpoint /api/user/<user_id>/summary and because the user does not exist, NEXT returns a 404 error: 

`{"message":"Not Found: No user with the id CN=svc_adds_unowned,OU=Windows,OU=Production,OU=Services,OU=Accounts,DC=clouddev,DC=corporate,DC=t-mobile,DC=com exists","code":404}`

![bug-role-owner-animation](https://user-images.githubusercontent.com/14936566/53994233-90f2d580-40e6-11e9-87ff-d1d6e7dcc94b.PNG)

**Comment by PatrickLammers** [comment]
also, this seems to break the ChatBot.  You cannot join any group like this because the submit button doesn't paint.

**Comment by PatrickLammers** [comment]
we can address this at T-Mo by fixing the source data -- but the app should be able to deal with this scenario.  Do we log these issues as we import?  Do we display an error?  Can a SysAdmin override?

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
