### ISSUE TITLE
 Restrict User to create duplicate role and pack names 

### ISSUE THREAD

**Issue by satkeeva** [hyperledger/sawtooth-next-directory#1354]
[User Story] [Epic] | Restrict User to create duplicate role and pack names
----------|----------
Epic Title | (Epic NAME)
User Story Title |  Restrict User to create duplicate role and pack names
T-shirt size: S(mall), M(edium), L(arge) | 
Description | Resource names should be globally unique to avoid collisions in client
Acceptance Criteria/Tests |  If a user attempts to create a role or pack that would conflict with an existing name, he/she is given a pop-up window that informs them the name already exists.  When dismissed, the focus will be back onto the name creation edit control so I'm ready to rename the role/pack.

**Comment by satkeeva** [comment]
This story is connected to #778. #778 takes care of backend, #1354 handles the frontend

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
