### ISSUE TITLE
[Bug] Client displays invalid/unavailable dates in proposal tables

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#1356]
Bug | Client displays invalid/unavailable dates in proposal tables
----------|----------
Expected behavior | Client should display valid dates
Actual behavior | See title
Repro steps | TBD
Build | which build number exhibits the issue?
Severity | 2
Details/Notes | Any more observations...

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
