### ISSUE TITLE
[Bug] Invalid attempt to spread non-iterable instance error

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#1362]
Bug | Invalid attempt to spread non-iterable instance error
----------|----------
Expected behavior | No errors
Actual behavior | Error
Repro steps | Detailed instructions so anyone can see the error.
Build | which build number exhibits the issue?
Severity | 2
Details/Notes | `Invalid attempt to spread non-iterable instance error`

**Comment by Srinuthalapati** [comment]
![Error in NEXT Browse button](https://user-images.githubusercontent.com/23491817/54454102-f4e45200-4715-11e9-8ec9-1eaefe03fd77.JPG)

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
