### ISSUE TITLE
Remove old UI directory

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#137]
Task | Define removal of UI directory
----------|----------
Task Title | Remove old UI directory
User Story | TBD
Epic | Multi-party approval [#76](https://github.com/hyperledger/sawtooth-next-directory/issues/76)
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 1
Description | It is useful to remove this directory separately.
Business Need (the why): | -
Applications or Systems impacted | 
Dependencies | if certain tasks must be done in a certain order, note here
Assumptions | _if any_

**Comment by adamgering** [comment]
not until the new UI has basic functionality

**Comment by PatrickLammers** [comment]
hardly seems like "technical" debt...  more like just a clean up task that would make it easier for new people to ramp up.  Very low pri but we shouldn't lose it.

**Comment by PatrickLammers** [comment]
seems to be gone.... if you find it again, please delete it.
