### ISSUE TITLE
[Bug] Subordinates call is not working

### ISSUE THREAD

**Issue by mtn217** [hyperledger/sawtooth-next-directory#1392]
Bug | Subordinates call is not working
----------|----------
Expected behavior | When I visit the organization tab in NEXT UI, I should be able to see my subordinates in the org chart. 
Actual behavior | Subordinates is missing from the org chart.
Repro steps | Sign in as user with subordinates and visit organization tab.
Build | 0.7.1
Severity | 3. clunky but functional 
Details/Notes | This was due to part of NEXT ID implementation that has started in sprint 14.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
