### ISSUE TITLE
[Bug] LDAP Users aren't able to view their imported roles

### ISSUE THREAD

**Issue by mtn217** [hyperledger/sawtooth-next-directory#1393]
Bug | LDAP Users aren't able to view their imported roles
----------|----------
Expected behavior | When I try to view my AD roles in the Manage page, I don't see my AD roles.
Actual behavior | I don't see my AD roles listed in the Manage page.
Repro steps | Sign in with a user that owns a AD role
Build | 0.7.1
Severity | 2. blocks functionality
Details/Notes | Caused by the NEXT ID implementation that started in Sprint 14.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
