### ISSUE TITLE
Add indication of the source of a change

### ISSUE THREAD

**Issue by PatrickLammers** [hyperledger/sawtooth-next-directory#1395]
User Story | We need to know so we don't go in circles
----------|----------
T-shirt size: | 
User Story | "As a user of a next, the system needs to know where a change is coming from so we don't try to write back to the source of the change"
Description | Outbound should only write to AD if the change was made in the NEXT API, currently we don't know if changes are from AD or from NExt.  We need to add an indication of the source of the change.

**Acceptance Criteria/Tests** 
- verify that flag is present and correctly set for the source of the change.
- Integration tests exist and are passing
- this is only for roles & users (the stuff that would be written to AD)

**Comment by Srinuthalapati** [comment]
The new field/parameter that needs to be added to 'metadata' field would be - "**sync_direction**". This new key will be added after the 'pack_id' key in the 'metadata' field. The values for  "sync_direction" key would be either - **"INBOUND"** & **"OUTBOUND"**.

**Comment by Srinuthalapati** [comment]
Need to discuss more about prominence of the **metadata** field and **metadata** table, before I actually include the new key - **sync_direction** in the metadata field.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
