### ISSUE TITLE
Add Transport Layer Security to the application

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#149]
[EPIC] | Add TLS to the UI and Rest Api
----------|----------
T-shirt size: S(mall), M(edium), L(arge) | S
Story Points - Fibonacci (1,2,3,5,8,13) | 3
User Story | "As a Sawtooth NEXT consuming enterprise, I want my personally identifiable information to be protected in transit"
Description | Add TLS (https) to the UI and Rest Api
Business Need (the why): | Satisfy privacy laws
Details | Explore the HL projects for self-signed certs in pre-prod environments
Acceptance Criteria/Tests | The UI/rest api should be available at https://host:port
Additional Info | https://hyperledger.github.io/composer/v0.19/integrating/securing-the-rest-server

**Comment by PatrickLammers** [comment]
is there any PII in our data?  Adding PP label just in case....

**Comment by mtn217** [comment]
Closing out this ticket as it is a duplicate of #855. I have copied over the necessary details from this ticket over to 855.
