### ISSUE TITLE
BLOCKED [User Story] Create Docker Hub Images

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#156]
User Story | Create Docker Images
----------|----------
Task Title | Create Docker Hub Images
User Story | #224
Epic | 
T-shirt size default is S(mall) | M
Story Points - Fibonacci (1,2,3,5) | 5
Description | Application should be runnable with just a docker-compose YAML file pulling the latest images from docker hub.
Business Need (the why): | Ease of testability and deployment
Applications or Systems impacted | 
Dependencies | 
Assumptions |

**Comment by jbobo** [comment]
So we'll need a docker hub service account to host the images. It won't be too bad after that to push the images and change the docker-compose file to pull them.

**Comment by jbobo** [comment]
Working with @chrisspanton to determine where we'll host the images.

**Comment by agoldingay** [comment]
per 10/8 standup, adding Chris to assignees, too.

**Comment by jbobo** [comment]
@agoldingay could we move this to s4? @chrisspanton got in touch with Hyperledger and is getting permissions set up, but I'm not sure if we can depend on this to be finished by Monday.

**Comment by PatrickLammers** [comment]
story has zero traction with PO.  If we really need this, it will come back around I'm sure...
