### ISSUE TITLE
[User Story] Create System (Role) Accounts

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#157]
User Story | Create System (Role) Accounts
----------|----------
Epic Title | 
User Story Title | Create System (Role) Accounts
T-shirt size: S(mall), M(edium), L(arge) | M
Story Points - Fibonacci (1,2,3,5,8,13) | 8
User Story | Accounts for non-users (e.g. Active Directory sync)
Description | AD is going to nee a role
Business Need (the why): | 
Details | 
Additional User Story | 
Acceptance Criteria/Tests | 
Failure |
Definition of Done |                                                                  
UX/UI Details and/or mockups |
Applications or Systems impacted |
Dependencies |
Assumptions |
Performance Considerations |
Security Considerations | 
QA Considerations | 
Acrhitectural/System or Component Impacts | 
Reverse Engineering Required | 
Questions/Clarifications |

**Comment by adamgering** [comment]
This was not on the sprint

**Comment by PatrickLammers** [comment]
This is needed for the Next App to connect to AD, right?  Surely we have this...

**Comment by PatrickLammers** [comment]
after discussion with Ned, neither of us really know that this issue is talking about... someday we will surely trip over this issue again in the future if it is really needed.  For now, closing.
