### ISSUE TITLE
S3 [User Story] Azure Active Directory Import Research

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#158]
User Story | Azure Active Directory Import
----------|----------
Epic Title | [Epic] Active Directory Integration [#35](https://github.com/hyperledger/sawtooth-next-directory/issues/35))
User Story Title | T-Mobile Active Directory Import
T-shirt size: S(mall), M(edium), L(arge) | S
Story Points - Fibonacci (1,2,3,5,8,13) | 3
User Story | Import users, roles, etc, from Azure Active Directory
Description | The goal of this user story is to only complete research of azure active directory and see how it integrates with TMO
Business Need (the why): | 
Details | 
Additional User Story | 
Acceptance Criteria/Tests | 
Failure |
Definition of Done |                                                                  
UX/UI Details and/or mockups |
Applications or Systems impacted |
Dependencies |
Assumptions |
Performance Considerations |
Security Considerations | 
QA Considerations | 
Acrhitectural/System or Component Impacts | 
Reverse Engineering Required | 
Questions/Clarifications |

**Comment by codingalyona** [comment]
We need to break the user story into a smaller portion.

**Comment by chrisspanton** [comment]
Completed.
