### ISSUE TITLE
S3 [Task] Multi-Node Configuration

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#159]
Task | Multi-Node Configuration
----------|----------
Task Title | Multi-Node Configuration
User Story | #224
Epic | 
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 8
Description | Configuration that has multiple nodes
Business Need (the why): |
Applications or Systems impacted | 
Dependencies | 
Assumptions |

**Comment by yunhangc** [comment]
after conversation with Chris. might want to hold this off a bit
