### ISSUE TITLE
Azure (AAD) Authentication

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#160]
EPIC | Azure Active Directory Authentication
----------|----------
EPIC Title | Azure Active Directory Authentication
User Story | Azure Active Directory Authentication
Epic | #49
T-shirt size default is S(mall) | M
Description | Ability for a user to sign into NEXT using Azure AD credentials. Supports new user creation as well as logon. SSO: Finds and associates the user from the remote system (AAD).
Business Need (the why): | 
Applications or Systems impacted | 
Dependencies | An AD instance is available with user data to be accessed and synched in both directions
Assumptions |

**Comment by jbobo** [comment]
Working with @chrisspanton on getting a docker hub account set up for this

**Comment by adamgering** [comment]
Moved it back to grooming, not sure if Ned is actively working on this. If so, move back to in-progress. If not, anyone can pick it up.

**Comment by jbobo** [comment]
Still working on this, Might be good to leave it in grooming until next sprint, since we're working on a lot of AD integration on Tuesday.

**Comment by jbobo** [comment]
I think we need to figure this out after outbound sync for both LDAP and AAD (Issues #323 #324 #35 ). Ideally we would check user sign in against all AD providers that we'll be syncing with.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
