### ISSUE TITLE
[Task] Define Systems Administrators

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#162]
Task | Define Systems Administrators
----------|----------
Task Title | Define Systems Administrators
User Story |
Epic |
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 1
Description | 
Business Need (the why): | 
Applications or Systems impacted | 
Dependencies | 
Assumptions |

**Comment by PatrickLammers** [comment]
This is a story to write a story...  killing it.
