### ISSUE TITLE
[Task] Generate frozen executable for production distribution

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#168]
Task | Generate frozen executable for production distribution
----------|----------
Task Title | Generate frozen executable for production distribution
User Story | 
Epic |
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 3
Description | 
Business Need (the why): | 
Applications or Systems impacted | 
Dependencies | 
Assumptions | 

https://docs.python-guide.org/shipping/freezing/

**Comment by PatrickLammers** [comment]
The linked article suggests that good way of distributing your app is by creating a package that includes the dependencies so that users have a smooth install experience.  

Not worth tracking at this point
