### ISSUE TITLE
Write Rbac Processor Unit Tests

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#169]
Task | Write Rbac Processor Unit Tests
----------|----------
Task Title | Write Rbac Processor Unit Tests
User Story | #106 
T-shirt size default is S(mall) | M
Story Points - Fibonacci (1,2,3,5) | 3
Description | Increase unit test coverage of the rbac_processor module
Business Need (the why): | Unit tests facilitate code quality, ability to refactor, and self-documentation. Breaking out tests into smaller pieces increasing maintainability and also self-documentation.

**Comment by codingalyona** [comment]
Keith is working on unit testing - RBAC processor - refactoring and will incorporate in pairing. Will share with Richard to also be involved and looped in. @yunhangc

**Comment by kthblmfld** [comment]
The rbac_processor module will be easier to extend and test once similar features (validation, persistence, models, messages, etc) are logically grouped together. It appears the opposite is happening, likely the result of copy-pasting code. I am refactoring now into a design that should be easier to read/test/comprehend and will include tests in the change.

**Comment by PatrickLammers** [comment]
Replaced by issue #1173 now...
