### ISSUE TITLE
Write Ledger Sync Unit Tests

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#170]
Task | Write Ledger Sync Unit Tests
----------|----------
Task Title | Write Ledger Sync Unit Tests
User Story | #106 
T-shirt size default is S(mall) | M
Story Points - Fibonacci (1,2,3,5) | 3
Description | Increase unit test coverage of the ledger_sync module
Business Need (the why): | Unit tests facilitate code quality, ability to refactor, and self-documentation. Breaking out tests into smaller pieces increasing maintainability and also self-documentation.

**Comment by codingalyona** [comment]
@kthblmfld will invite @yunhangc to pairing session today. 
@devsatishm , please, provide Richard with scripts

**Comment by adamgering** [comment]
this was not on the sprint

**Comment by PatrickLammers** [comment]
Adam has assured me that ledger sync stuff has hit  very high code coverage level.  Is this story closeable?  Why should this only apply to ledger sync code... all code needs great tests.

**Comment by PatrickLammers** [comment]
Covered more extensively by stories #1180, #1181, #1182, #1183, #1184, #1185, #1186, #1187, #1188, #1189.  Closing this one.
