### ISSUE TITLE
[Story] Up-rev Sawtooth Version from 1.0 to 1.05

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#184]
[User Story] | Up-rev Sawtooth Version
----------|----------
T-shirt size: S(mall), M(edium), L(arge) | M
Story Points - Fibonacci (1,2,3,5,8,13) | 3
User Story | [Value Statement] "As an owner of the product, I want to ensure the product runs on a recent version of Sawtooth"
Description | Rev the versions of Sawtooth images from 1.0 to 1.05 in Docker/compose files
Business Need (the why): | Keeping Sawtooth up to date ensures the project is inheriting the latest bug fixes, security patches, performance improvements, and new library features.
Details | Up-rev the version, build/deploy the application, run tests, retrofit any incompatibilities that arise from the upgrade
Acceptance Criteria/Tests | The version of Sawtooth is 1.05, all tests pass, no unusual side effects are observed at runtime.

**Comment by PatrickLammers** [comment]
we should focus on #838 and close this one.
