### ISSUE TITLE
[PyLint] Review ignored modules

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#197]
Task | Task Title - TBD
----------|----------
Task Title | TBD
User Story | #224
Epic | TBD or NA
T-shirt size default is S(mall) | TBD
Story Points - Fibonacci (1,2,3,5) | TBD

This looks so overly broad I'm not sure we're linting hardly any files, esp. the rbac*

```ignored-modules=*.protobuf,sawtooth*,rbac*```

This removes the duplicate wildcards patterns Ned had in PR #195 

```ignored-modules=rbac_processor.protobuf,*.protobuf,*.*.protobuf,rbac*,rbac*.*,rbac*.*.*,sawtooth*,sawtooth*.*,sawtooth*.*.*,sawtooth_rest_api.protobuf,sawtooth_rest_api.messaging```

Verify we are catching lint errors in the .py files in rbac_processor and rbac_addressing, etc...

**Comment by jbobo** [comment]
With my initial PR, after running `bin/build -p` it gave no errors. As it stands it does return errors after building the protobuf modules.

**Comment by nadiabahrami** [comment]
Along with issue #218 this is now narrowed down in PR #258 E1101 was added to the ignore list as the protos build dynamically and was getting false positives.   Modules to be ignored are now very specific and will be eliminated as we implement them in the repo.
