### ISSUE TITLE
[Pylint] Document ignored rules

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#198]
Task | Task Title - TBD
----------|----------
Task Title | TBD
User Story | #224
Epic | TBD or NA
T-shirt size default is S(mall) | TBD
Story Points - Fibonacci (1,2,3,5) | TBD

Add commented documentation on the rules that are ignored and why in setup.cfg

```ignore=R,C,E501,E203,W503,W0715,W0613```

**Comment by jbobo** [comment]
@adamgering Would adding comments to setup.cfg be acceptable, or do we want this somewhere else, like README, etc.?
