### ISSUE TITLE
Role owners do not have permissions to add/delete members and admins

### ISSUE THREAD

**Issue by mtn217** [hyperledger/sawtooth-next-directory#20]
When a role owner attempts to add or delete members and admins to/from their role, the following error message is outputted:
```
{
    "code": 400,
    "message": "Bad Request: Txn signer 03fdda9a0d513e870d45c0cc1acfd2fb3df234bc284b4d34397f8bba29c6c8d410 is not the user or the user's manager ['022b5e227f51fd5713d629fe75206d60a562aaea3c8fb59a52f8cfc2e494f6850a', '']"
}
```

It appears role owners can only add or delete members or admins only if the role owner is the manager of the targeted user or they are the user themselves. Role owners should have full control of their role and they should have the ability to add/delete any user even if the owner is not the manager of the targeted user or the user being added/deleted. 

### Scenario
The owner of role `c5e52d53-68e7-437e-b9b6-27afec9a1f29` would like to delete the role member with the user id `022b5e227f51fd5713d629fe75206d60a562aaea3c8fb59a52f8cfc2e494f6850a`

Here is the CURL request for this operation:
`$ curl -X DELETE "http://localhost:8000/api/roles/c5e52d53-68e7-437e-b9b6-27afec9a1f29/members" -H "accept: application/json" -H "Authorization: role_owner's_bearer_token" -H "Content-Type: application/json" -d "{ \"id\": \"022b5e227f51fd5713d629fe75206d60a562aaea3c8fb59a52f8cfc2e494f6850a\"}"
`

### Expected Result
A proposal would have been created with the type REMOVE_ROLE_MEMBERS and the response would have contained the proposal ID.
```
{
  "proposal_id": "63467642-6067-4c82-a096-1a1972d776b3"
}
```

### Actual Result
```
{
    "code": 400,
    "message": "Bad Request: Txn signer 03fdda9a0d513e870d45c0cc1acfd2fb3df234bc284b4d34397f8bba29c6c8d410 is not the user or the user's manager ['022b5e227f51fd5713d629fe75206d60a562aaea3c8fb59a52f8cfc2e494f6850a', '']"
}
```

**Comment by yunhangc** [comment]
this should be addressed by PR18

**Comment by yunhangc** [comment]
PR18 merged.
