### ISSUE TITLE
[User Story] Secrets Storage

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#206]
[User Story] | Secrets Storage
----------|----------
User Story Title | Secrets Storage
T-shirt size: | L
Story Points | 13
User Story | Ability for the application to load secret keys
Description | Application needs the ability to securely store and load private and secret keys.
Details | Services such as the Transaction Batcher, and Active Directory Sync will sign transactions, and thus will need access to private keys. Also, presently user keys are encrypted, and thus the key used for encrypting those keys must be securely stored.

**Comment by PatrickLammers** [comment]
related to #590

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
