### ISSUE TITLE
S7 [User Story] Refactor Rbac Processor by Message (Library)

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#210]
Dependency of #379

Task | Refactor Rbac Processor by Message (Library)
----------|----------
Task Title | Refactor Rbac Processor by Message (Library)
User Story | #106 
T-shirt size default is S(mall) | M
Story Points - Fibonacci (1,2,3,5) | 2
Description | Refactor rbac_processor to implement message classes for verification and storage.
Business Need (the why): |

**Comment by adamgering** [comment]
reduced points to 2 based on completed work

**Comment by adamgering** [comment]
Waiting on pre-req PR #686
