### ISSUE TITLE
[Bug] Support Transaction Processor Restarts

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#211]
Task | Support Transaction Processor Restarts
----------|----------
Task Title | Support Transaction Processor Restarts
User Story | 
Epic | 
T-shirt size default is S(mall) | 
Story Points - Fibonacci (1,2,3,5) | 
Description | When the transaction processor is restarted, the validator removes it, and it does not reconnect.
Business Need (the why): | 
Applications or Systems impacted | 
Dependencies | 
Assumptions | 

```docker-compose -f docker-compose.yaml -f docker-dev.yaml restart rbac-tp```

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
