### ISSUE TITLE
[User Story] Container Connectivity Resilience

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#214]
[User Story] | Container Connectivity Resilience
----------|----------
Epic Title | #213 
User Story Title | Container Connectivity Resilience
T-shirt size: S(mall), M(edium), L(arge) | L
Story Points - Fibonacci (1,2,3,5,8,13) | 8
Description | Application components should monitor their connectivity to each other and reconnect if disconnected
Business Need (the why): | Chaos
Acceptance Criteria/Tests |  in a running stable system, cause the connection between components to drop (kill processes?  disconnect?) and observe that system recovers to stable state.  the drop should be logged for future diagnosis.
Reverse Engineering Required | Sawtooth Core source
Questions/Clarifications |

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
