### ISSUE TITLE
SMTP Connector

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#215]
[User Story] | SMTP Connector
----------|----------
Epic Title | 
User Story Title | SMTP Connector
T-shirt size: S(mall), M(edium), L(arge) | M
User Story | The application should be able to send email
Description | Probably best to use a new rethink table to manage an outbound SMTP queue, and have a new service that reads from that queue and sends emails. Bonus points for open or read receipt tracking.
Business Need (the why): | Email Verification, Notifications for NEXT platform
Acceptance Criteria/Tests |  Emails should be sent out when the following occurs: user requesting access to a group, user requests to reset password or obtain username, more TBD.

- [ ] Implement function responsible for sending email
- [ ] Integrate email function with TMO exchange server (https://pypi.org/project/exchangelib/  ?)
- [ ] Get service account/credentials for NEXT app from TMO OPs
- [ ] Create a queue for buffering email messages
- [ ] Create a listener that picks up and sends emails

**Comment by adamgering** [comment]
#389 was a duplicate of this story, yes. However, the title has been changed on #389 such that that is no longer clear. This story covers only the daemon, queue, sending and related tracking.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
