### ISSUE TITLE
S3 [Task] Validate Local Dev Dependencies

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#217]
Task | Validate Local Dev Dependencies
----------|----------
Task Title | Validate Local Dev Dependencies
User Story | #224 
Epic | 
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 3
Description | Validate local dev dependencies (python packages, paths, etc) such that the linter, pytest and the editors/IDEs behave well.
Business Need (the why): | 
Applications or Systems impacted | 
Dependencies | 
Assumptions |

**Comment by adamgering** [comment]
Do we need PYTHONPATH environment variable configured?

**Comment by agoldingay** [comment]
@jbobo will address options on the project chat.

**Comment by jbobo** [comment]
From Amundson: 

>we only publish the SDK to pypi; for the rest API and validator, we package debian packages and docker images. rest api will be rewritten in rust at some point, so focusing on python distribution mechanisms isn't necessarily the best long-term option

>are you modifying the rest api? I'm not sure why you would care about linting the sawtooth rest api unless you are coding on it.
>it's not library code

I think we should just add `sawtooth-rest-api*` to `--ignored-modules` in `./setup.cfg`. At that point we can prepend 
```
pykg-config==1.3.0
secp256k1==0.13.2
grpcio-tools==1.15.0
```
to `./setup.cfg` and we're good to go, the documentation that @nadiabahrami wrote will be OS agnostic and should work for everyone.

**Comment by nadiabahrami** [comment]
Tried to implement above and was unable to replicate successfully.  Currently blocked, but will be meeting with @jbobo on Monday 10/12/18 to come to an acceptable conclusion and close out this ticket.

**Comment by nadiabahrami** [comment]
The doc setups is done currently.  Ticket has been made for setup.py
