### ISSUE TITLE
[Issue][Bug] Multiple methods of linting return different results

### ISSUE THREAD

**Issue by jbobo** [hyperledger/sawtooth-next-directory#218]
S3 [Task] | Multiple methods of linting return different results
----------|----------
Task Title | Multiple methods of linting return different results
User Story | #224
Epic | N/A
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 3
Description | We currently have 3 documented methods of running our linter. All 3 methods return different output. We need to find out why this is and either normalize all 3 methods and document their use, or decide on one method as the source of truth and deprecate the others.
Business Need (the why): | Having multiple linters that return differing output for the same source code has the potential to cause a lot of miscommunications.
Applications or Systems impacted | linter, pylint, pycodestyle
Dependencies | Issue #101 , #150 , #197 , #198 , PR #195 , #196 are dependent on this.
Assumptions | _N/A_

**Comment by jbobo** [comment]
we have these methods that I've found so far:

- `./bin/run_lint' on the local machine from the root project directory.

- `./bin/build -l` on the local machine from the root project directory.

- `./bin/start` on the local machine from the root project directory, then `docker exec -it rbac-shell bash` to open an interactive terminal in ht rbac-shell container, and running `bin/run_lint` from inside of the container.

All 3 methods produce different results and have already caused miscommunications between contributors. Looking into rbac_shell's `Dockerfile`, `bin/run_lint` and `bin/build -l` to figure out why this is happening.

**Comment by mtn217** [comment]
FYI `.travis.yml` has this in lines 7 and 8. 
```
script:
   - bin/build -p && bin/build -i
```

**Comment by jbobo** [comment]
`./bin/build` lines 60-64:

```
 l)
    info "Running lint"
    docker build . -f tests/Dockerfile -t rbac-test-env
    docker run --rm -v $(pwd):/project/tmobile-rbac rbac-test-env bin/run_lint
    ;;
```

**Comment by jbobo** [comment]
`./shell/Dockerfile` installs python3-sawtooth-sdk, and python3-sawtooth-rest-api through APT, which may be why it's showing different output for `./bin/run_lint`

**Comment by jbobo** [comment]
So it looks like `bin/build -l` is running `./bin/run_lint` in the `rbac-test-env` container. At least we're using the same script in each method. But, we're using different environments for each of the available methods. We should decide on a single environment to use for everything. `bin/build -l` Is the only options that returns no errors with the current `setup.cfg` file, so I'd prefer to go with that. I'll test and make sure it'll pick up legitimate errors, and see if there's a way for us to use it in travis.

**Comment by jbobo** [comment]
sawtooth-next-directory/shell/Dockerfile and sawtooth-next-directory/tests/Dockerfile are equivalent environments. Recommending we use `./bin/build -l` for travis and testing (and for the time being development), and after we work out a documented method for building dev environments, use `./bin/run_lint` for development.

**Comment by nadiabahrami** [comment]
./bin/build -i was keeping the image from previous runs and would not report the same errors.  This has been amended in the build script.  Now running ./bin/build -l and ./bin/run_lint will result in the same results.  The code is in PR #258
