### ISSUE TITLE
[Task] | Integrate test coverage report with Travis

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#228]
Task | Integrate test coverage report with Travis
----------|----------
Task Title | Integrate test coverage report with Travis
Epic | Establish a high code quality standard
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 2
Description | Integrate the test coverage report described in #161 with Travis such that test coverage of backend systems is reflected in Travis UI/widgets
Business Need (the why): | Having test coverage integrated with Travis allows stakeholders to monitor coverage levels/trend in real-time.

**Comment by adamgering** [comment]
Delivered by #399
