### ISSUE TITLE
Establish minimum python unit test coverage percentage (80%)

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#231]
Task Title | Establish minimum test coverage percentage (80%)
----------|----------
Epic | Establish a high code quality standard
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 2
Description | Configure builds in Travis to fail when code coverage emitted from #161 and #228 falls below 80%
Business Need (the why): | Having builds fail when coverage drops ensures developers don't add new features that aren't properly tested
Preconditions | Unit tests in #106 need to cover more than 80% of the Python code

**Comment by PatrickLammers** [comment]
closing stories that aren't getting traction
