### ISSUE TITLE
Add CODEOWNERS to repo

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#232]
Title | Add CODEOWNERS to repo
----------|----------
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 2
Description | See https://github.com/hyperledger/sawtooth-seth/blob/master/CODEOWNERS
Business Need (the why): | This file helps track default reviewers over time. Having default reviewers auto-populate upon opening a PR increases productivity/collaboration, reduces the likelihood of code changes falling off anybody's radar

**Comment by PatrickLammers** [comment]
Not needed for V1.  Administrative overhead
