### ISSUE TITLE
Activate linting policy for too-many-args

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#233]
User Story | Activate linting rule for too-many-args
----------|----------
T-shirt size | M 
Story Points - Fibonacci (1,2,3,5) | 5
Description | Too many arguments is a code smell for a more simple design. The linter rule for this has been disabled while linting is being incorporated into build automation (get linter running first, fix violations incrementally). This rule was identifying violations before disablement, so we know there are at least a few cases of it in the python code. Enable the rule locally, fix the violations, and push the new policy. 
Business Need (the why): | Fewer args in functions implies the code is easier to comprehend and less likely to include side effects.

**Comment by nadiabahrami** [comment]
duplicate issue
