### ISSUE TITLE
[Task] Add rebasing instructions to the wiki

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#241]
Task | Add rebasing instructions to the wiki
----------|----------
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 2
Description | Add step-by-step instructions to this page: https://github.com/hyperledger/sawtooth-next-directory/wiki/Git-Pull-Requests describing how to go about squashing commits within a PR
Business Need (the why): | Having a document to reference will improve productivity by serving as a means of correction when new contributors are challenged to fix their commits in PRs

**Comment by nadiabahrami** [comment]
Verbal approval from Keith
