### ISSUE TITLE
Catch Transaction Processor Exceptions

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#245]
Task | Catch Transaction Processor Exceptions
----------|----------
Task Title | Catch Transaction Processor Exceptions
User Story | 
Epic | #213 
T-shirt size default is S(mall) | M
Story Points - Fibonacci (1,2,3,5) | 3
Description | Transaction processor should catch exceptions rather than exit
Business Need (the why): | 
Applications or Systems impacted | 
Dependencies | 
Assumptions |

**Comment by adamgering** [comment]
@kthblmfld Should the refactored TP now catch exceptions? I'll rebase and try to reproduce if so.

**Comment by PatrickLammers** [comment]
Not really a sub task of a story... more like missing functionality we need to add.

**Comment by PatrickLammers** [comment]
closing for now -- will create stories for any exceptions we actually see
