### ISSUE TITLE
Describe missing removal rejections/confirmations in spec

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#249]
Task | Describe missing removal rejections/confirmations in spec
----------|----------
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 1
Description | There are unimplemented functions for role_[owners,members,admins]: REJECT_REMOVE_ROLE_[ADMINS/OWNERS/MEMBERS/TASKS] and CONFIRM_REMOVE_ROLE_[ADMINS/OWNERS/MEMBERS/TASKS]. Specify the expected behavior in the Spec for roles here: https://github.com/hyperledger/sawtooth-next-directory/wiki/Roles, proposals" https://github.com/hyperledger/sawtooth-next-directory/wiki/Proposals or mark this issue as no longer required as a feature.
Business Need (the why): | Currently these functions called, but the implemented function signatures are not present in git history.

**Comment by PatrickLammers** [comment]
closing after review with George
