### ISSUE TITLE
S4 [User Story] Add create user functionality

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#266]
User Story | Add create user functionality
----------|----------
User Story Title | Add create user functionality
User Story | Existing API Integration [#263](https://github.com/hyperledger/sawtooth-next-directory/issues/263)
Epic | Multi-party approval [#76](https://github.com/hyperledger/sawtooth-next-directory/issues/76)
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 3
Description | Client should create a new user and redirect to landing page. Use old client as reference.
Business Need (the why): | -
Applications or Systems impacted | -
Dependencies | -
Assumptions | -

**Comment by Akashkotian7** [comment]
@pgobin  need further explanation on what needs to be done
