### ISSUE TITLE
[Epic] Multi-party approval

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#27]
Epic | Multi-approval Approval
----------|----------
Task | Multi approval approval
Epic Title | Multi-Party Approval #76 
User Story Title | Multi-party approval
Statement |As a user of NEXT, I want to define the eligible roles so I can enable multi-party approvals
Description | 
Business Need (the why): | multi-party approval functionality

**Comment by codingalyona** [comment]
design conversation needs to happen - documentation needs to come out of it.

**Comment by PatrickLammers** [comment]
This isn't a "true epic" in that it has no child stories.  There are other Epics related to Multi-party approval so we will use those instead.
