### ISSUE TITLE
Active Directory (LDAP) Authentication

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#271]
Epic Title | Active Directory Authentication
----------|----------
Epic Title | Active Directory Authentication
T-shirt size default is S(mall) | M
Story Points - Fibonacci (1,2,3,5) | 5
Description | The NEXT platform should have the ability for an AD user to sign in using their AD credentials. The NEXT platform should have the user's account already imported from AD. When the user successfully logs in, they should see their account details from AD.
Business Need (the why) | AD users should be able to log in to NEXT because the NEXT platform should be the main tool used for the management (granting access, updating, deleted, etc.) of AD roles. 
Dependencies | AD Inbound Initial + Delta Sync

**Comment by PatrickLammers** [comment]
added a story to this epic which means it moves to next sprint
