### ISSUE TITLE
S4 [Task] Store AAD endpoint configuration

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#273]
Task | Store AAD endpoint configuration
----------|----------
Task Title | Store AD endpoint configuration
User Story | #49 
Epic | #35 
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 1
Description | Store the AAD endpoint values
Business Need (the why): | 
Applications or Systems impacted | 
Dependencies | 
Assumptions |

**Comment by jbobo** [comment]
we currently use the Environment variables AUTH_TYPE, TENANT_ID, CLIENT_ASSERTION, CLIENT_ID, and CLIENT_SECRET for AAD, (see PR #314 and PR #309)
