### ISSUE TITLE
S4 [Task] Define AD Group Protobuf

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#285]
Task | Define AD Group Protobuf
----------|----------
Task Title | Define AD Group Protobuf
User Story | #50 
Epic | #35 
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 1
Description | Define AD (LDAP) User data protobuf
Business Need (the why): | 
Applications or Systems impacted | 
Dependencies | 
Assumptions |

**Comment by agoldingay** [comment]
Scrum team doesn't think valid. Closing
