### ISSUE TITLE
S4 [Task] Access AAD Test Environment

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#286]
Task | Access AAD Test Environment
----------|----------
Task Title | Access AAD Test Environment
User Story | #49 
Epic | #35 
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 1
Description | Access AAD Test Environment
Business Need (the why): | 
Applications or Systems impacted | 
Dependencies | 
Assumptions |

**Comment by agoldingay** [comment]
Nadia completed this on different issue.
