### ISSUE TITLE
S4 [Task] Access AD Test Environment

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#287]
Task | Access AD Test Environment
----------|----------
Task Title | Access AD Test Environment
User Story | #50 
Epic | #35 
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 1
Description | Access AD (LDAP) Test Environment
Business Need (the why): | 
Applications or Systems impacted | 
Dependencies | 
Assumptions |

**Comment by mtn217** [comment]
AD test environment access information has been provided by Chris Spanton. The information provided has been tested and we do have access to the AD test environment.
