### ISSUE TITLE
S4 [Task] Create AAD Application

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#292]
Task | Create AAD Application
----------|----------
Task Title | Create AAD Application
User Story | #49 
Epic | #35
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 1
Description | 
Business Need (the why): | 
Applications or Systems impacted | 
Dependencies | 
Assumptions |

**Comment by mtn217** [comment]
Satish created the AAD application to access one of T-Mobile's AAD test instances. This app will allow our developers to access the test AAD data.
