### ISSUE TITLE
Create setup.py

### ISSUE THREAD

**Issue by jbobo** [hyperledger/sawtooth-next-directory#293]
Task | Create a setup.py file for instantiating dev environments.
----------|----------
Task Title | Create setup.py
User Story | N/A
Epic | N/A
T-shirt size default is S(mall) | m
Story Points - Fibonacci (1,2,3,5) | 2
Description | We've got local dev dependencies figured out so now we need to create a setup.py file that'll pull in requirements.txt and install local dependencies.
Business Need (the why): | We need to be able to quickly onboard new contributors.
Applications or Systems impacted | 
Dependencies | N/A
Assumptions | N/A

**Comment by PatrickLammers** [comment]
Tasks are work items that relate to a user story...  This just sounds like a little bit of work to do.

**Comment by PatrickLammers** [comment]
if we haven't done this by now, we don't need it.
