### ISSUE TITLE
Explore Travis CI Integration for repo

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#30]
Prefer to enable this plugin in order to make new team/contributors onboarding smoother

**Comment by agoldingay** [comment]
@devsatishm tried to enable Travis CI, went to the Sawtooth NEXT Contributors space and updated to "maintainer". But that didn't work.

**Comment by devsatishm** [comment]
We'll need better permissions to enable Travis or any other plugin in this repo in the future.

I see this - 
"You don't have sufficient rights to enable this repo on Travis. 
Please contact the admin to enable it or to receive admin rights yourself."

**Comment by chrisspanton** [comment]
On it! Bear with me...

**Comment by devsatishm** [comment]
`.travis.yml` is pushed to `master`.  Travis CI should kick in whenever we enable the integration.

**Comment by agoldingay** [comment]
Anyway we can get this tested to confirm this is working as expected?

**Comment by agoldingay** [comment]
Next steps: Repo admin need to test. Will defer to Chris for help

**Comment by agoldingay** [comment]
will reach out to Chris. Then will get on chat forum to find the owner for the Git NEXT repo.

**Comment by devsatishm** [comment]
This looks good now! Travis is now enabled!

**Comment by devsatishm** [comment]
https://github.com/hyperledger/sawtooth-next-directory/pull/42  should enable this integration.
