### ISSUE TITLE
[User Story] Add ability to select manager

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#301]
User Story | Add ability to select manager
----------|----------
Epic Title | (Epic NAME)
User Story Title | (Story NAME)
T-shirt size: S(mall), M(edium), L(arge) | 
User Story | As a user, I want the ability to select the manager of a given user ?
Description | A short description 
Acceptance Criteria/Tests | The list of tests or criteria to be used to validate the story has been completed. May still need UAT or SIT / integration testing with other stories.

**Comment by PatrickLammers** [comment]
Tentatively setting this to be part of Hierarchical epic until I hear otherwise...

**Comment by PatrickLammers** [comment]
Describing functionality that already exists... Closing
