### ISSUE TITLE
[User Story] Create test data loader for outbound_queue in RethinkDb

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#312]
Committed, but uncaptured - S4 carryover

Title | Create test data loader for outbound_queue in RethinkDb
----------|----------
User Story | #311
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 2
Description | Write a simple Python file that opens a connection to RethinkDb and writes some content to the outbound_queue table
Business Need (the why): | Demonstrates functionality of outgoing AD sync
Applications or Systems impacted | Active Directory test environment

**Comment by nadiabahrami** [comment]
Closing as unneeded.  Testing will be the replacement for this.
