### ISSUE TITLE
Hierarchical Approval V1

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#32]
Epic | Hierarchical Approval
----------|----------
Functionality | Managers should have the ability to approve what their descendants (including direct reports) would be able to approve. 
Description | 
Stakeholders | requester (manager, next level up), requestee
Related | Approval engine, Epic #64 
Acceptance Criteria/Tests | See bulleted list below
Assumptions | 1) Requestor is authorized to approve for requestee. 2) Requestor and Requestee are valid entities 3) Requestor's next level up approver is a valid entity
Questions |

Acceptance Criteria:
- if manager approves/rejects, we write to the ledger "Manager on behalf of Approver..." so we can clearly see who took the action.
- The original approver should be able to see the manager's approve/reject with manager's name in the recent approvals page.
- the Manager should *also* see the their own name and on behalf of in their recent approval's page.
- if mgr's mgr takes the action we only record & display one level of 'on behalf of' -- (eg. don't show "Jon approved on behalf of Sue on behalf of Kevin on behalf of Amy"  just show "Jon approved on behalf of Amy"   (Or do we need to record this in ledger for audit so we know the state of the org structure at the time?)

@chrisspanton notes on Hierarchical Approval
This one is more difficult from a UI standpoint, because it's not clear where exactly you should see the Pending Requests for your direct reports.
If you can view "yourself" (profile page), then presumably you should be able to see your Direct Reports or even your Org Hierarchy on that page; and be able to click through on any of those people and see "their page".
On their page, recognizing that you are the manager or an ancestor, if you can see that user's view of their Pending Requests, you should be able to approve them on behalf of that user.
That user should be able to see recently approved Requests, and view that it was approved by another person on their behalf.
From a security standpoint, they ought to be able to Revoke that approval, and from an auditing standpoint it would be valuable in my opinion to allow them also to Confirm that approval. CC @chrisspanton

**Comment by yunhangc** [comment]
@chrisspanton Chris, how does the system know that I am out of the office or cannot perform the approval? Is there a flag I need to set up so that when I am unavailable for approval, I flip the flag and after I am back to office, I flip it again?

**Comment by adamgering** [comment]
writing test infrastructure for testing hierarchical approval

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
