### ISSUE TITLE
S5+ [User Story] AAD Delta Sync

### ISSUE THREAD

**Issue by jbobo** [hyperledger/sawtooth-next-directory#323]
[User Story] [Epic] | Multi-party approval, Approval configuration
----------|----------
User Story Title | 
T-shirt size: S(mall), M(edium), L(arge) | M
Story Points - Fibonacci (1,2,3,5,8,13) | 5
User Story | "As an administrator of the NEXT platform implementing NEXT into my organization, I want to have the ability to import my organization's Active Directory data (users and groups) into NEXT. I need the data to be on the platform to perform RBAC duties"
Description | An Active Directory data inbound queue is needed to allow organizations to integrate their existing users and groups into the NEXT platform. Two syncs will be created. The first sync is the initial sync that pulls all the data from an organization's AAD and queues it up to be saved on the Sawtooth network. The second sync will be the delta sync. The delta sync will be used to grab any differences from the last inbound sync (could either be a initial sync or a delta sync). Both syncs will be send data to a new RethinkDB table called ad_inbound_queue.
Business Need (the why): | To allow for organizations to easily adopt the NEXT platform for their RBAC management, the platform should include an option to import users from AAD. This inbound queue will store all the records from AAD before it gets saved on the Sawtooth blockchain.
Details | AAD Initial Sync, AAD Delta Sync, New Inbound Queue table RethinkDB
Additional User Story | S4+ [User Story] LDAP AD Inbound Queue #321
Acceptance Criteria/Tests | 1) Have a new RethinkDB table called ad_inbound_queue 2) Initial sync function to grab all AAD data and add those records to ad_inbound_queue 3) Delta sync function to grab differences in AAD data from last sync and add those records to ad_inbound_queue.
Failure | Not all data records from AAD were imported to ad_inbound_queue
Definition of Done | Both syncs reflects the latest version of AD data and adds that data to the ad_inbound_queue table.                                                                                          
UX/UI Details and/or mockups | if UI change, a mockup or description of what to change, attach image/file
Applications or Systems impacted | Access to AAD test environment
Dependencies | no story dependencies
Assumptions | N/A
Performance Considerations | Syncs should be as efficient as possible as AAD could contain a large set of data.
QA Considerations | Large AAD data imports
Acrhitectural/System or Component Impacts | if we're adding something new or significantly changing architecture flag for architect review

*AAD = Azure Active Directory

**Comment by agoldingay** [comment]
Carry over from Sprint 4 as this was committed to be complete.

**Comment by nadiabahrami** [comment]
Covered by three other tickets. closing for dups
