### ISSUE TITLE
Expiration of Access

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#33]
User Story | Expiration of Access
----------|----------
Epic Title | Expiration of Access
User Story | "As a manager, app/system access for my direct reports to expire automatically as per policy so I don't have to manually expire each person's permission"
Description | Role entitlements may be set to expire after owner-defined period as per policy
Business Need (the why): | mgr and group owner has to approve it. Go to multi-party approval. build configurable access so it's intelligence and has logic
Details | Access expires every 6 months. (need to be configurable)
Additional User Story | _linked_
Acceptance Criteria/Tests | _The list of tests or criteria to be used to validate the story has been completed. May still need UAT or SIT / integration testing with other stories.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
