### ISSUE TITLE
Re-Authorization of Access - manager set policy

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#34]
Epic | Re-Authorization of Access
----------|----------
Epic Title | Re-Authorization of Access
User Story | "As a manager I want to extend app/system access for my direct reports whose access are set to expire per policy without having to manually manage each pending expiration."
Description | Re-Authorization process for continuation of access after expiration per policy.
Business Need (the why): | dependency on Expiration of access. If groups of Rebellion that have hundreds of devs. Make the approval consumable to the user. A list?

**Comment by adamgering** [comment]
this was not on the sprint

**Comment by PatrickLammers** [comment]
related to #862

**Comment by PatrickLammers** [comment]
related to #84

**Comment by PatrickLammers** [comment]
This functionality is  taken care of by Batch approval already.  Closing.
