### ISSUE TITLE
[Epic] Active Directory Integration

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#35]
Epic | Active Directory Integration
----------|----------
Epic Title | Active Directory Integration
T-shirt size: S(mall), M(edium), L(arge) | L
Description | Integration between NEXT and Active Directory (Cloud and on-prem). (NEXT Integration Engine)
Business Need (the why): | 
Stakeholders | 
Details | Collaboration w/MS and Intel teams
User Scenarios | Integration between NEXT and Azure Active Directory (AD) cloud #49; and integration between NEXT and Active Directory (AD) on-prem #50
Acceptance Criteria/Tests | _The list of tests or criteria to be used to validate the story has been completed. May still need UAT or SIT / integration testing with other stories._
Failure | _if any, fold in negative tests_
Definition of Done | _e.g.Passes all regression tests, Passes testing per acceptance criteria, Approved by UI team, Able to show feature in demo_                                                                                                    
UX/UI Details and/or mockups | _if UI change, a mockup or description of what to change, attach image/file_
Applications or Systems impacted | _upstream/downstream applications/systems_
Dependencies | configuration 2 NEXT integrations
Assumptions | _if any_
Performance Considerations | _Will the work performed as part of this story impact system performance. If there is potential for a performance hit, where would you expect it to manifest in the system._
Security Considerations | _E.g., does this story involve working with Personal Identifying Information (PII)? Note any such security sensitive aspects._
QA Considerations | _what might be hard to test or test setup criteria_
Acrhitectural/System or Component Impacts | _if we're adding something new or significantly changing architecture flag for architect review_
Reverse Engineering Required | _to document areas not known well by dev team_
Questions/Clarifications | _Create new issue (add label: question) in this repo and link to this issue_

**Comment by agoldingay** [comment]
Technical work with Microsoft set for mid Oct.

**Comment by mtn217** [comment]
Closing issue because we have broken up this epic.
