### ISSUE TITLE
Add Swagger UI to the project

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#352]
The project has an openapi document that has been manually maintained over time.

It will need Swagger pages that deploy along with the rest-api per future integration plans within the TMO services ecosystem ( Integration with Clearwater repo )

Compare a few options and implement the most well-maintained, user-friendly solution.

A few to options to start looking into:
https://pypi.org/project/sanic-swagger/
https://pypi.org/project/sanic-attrs/

**Comment by PatrickLammers** [comment]
duplicate of #869??

**Comment by satkeeva** [comment]
I am working on #869 which appears to be a duplicate of #352. Closing #352 since #869 is in progress
