### ISSUE TITLE
[GitHub] What permission sets can we create on the repo?

### ISSUE THREAD

**Issue by adam-gering** [hyperledger/sawtooth-next-directory#36]
Looks like Wiki is either public (every Github user) or private (only users with push access).

Looks like Project is ready-only for everyone but users with push access.

Looks like Issues can be created with read-only access, but no assignment can be performed (Assignees, Labels, Projects and Milestones).

Issue Templates can only be created by repo maintainers (in Settings).

Looks like Pull Request can be made with read-only access.

**Comment by chrisspanton** [comment]
Looks like group permissions for sawtooth-next-contributors are resolved. Access there is the path forward for new team members. Access needs to be requested through the Hyperledger Helpdesk.
