### ISSUE TITLE
Batch Approval

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#37]
Epic | Batch Approval
----------|----------
Epic Title | Batch Approval
User Story | As a NEXT user, I want to approve or disapprove multiple application/system requests in one session so I don't have to retrieve each request one at a time.
Description | Ability to approve requests in a batch
Business Need (the why): | Approval engine feature. Built-in intelligence in the engine.
Additional User Story | all approval types in scope: expiration, re-authorization of access, new access
Acceptance Criteria/Tests | A NEXT admin can approve a bulk number of requests from the UI  There should be UI where role/pack owner can select which of the pending requests to process and then which result (so pick 3 of the 5 pending and approve, then pick the remaining 2 and reject).  Should also have the ability to simply "select all."
Definition of Done | Moments after an admin selects a batch of users and clicks "Approve", the approvals will be evident in Sawtooth and queries against RethinkDb                                                                                   
Questions/Clarifications | 12/7 - Keith: Regarding the "engine" described above: I believe we have settled on (at least initially) multi-approvals being carried out on the UI as a series of individual approvals processed in a loop. That is, the rest api doesn't require an additional endpoint for batch approval (just the existing single approval).

**Comment by PatrickLammers** [comment]
added more descriptive Acceptance Tests so we capture the idea of using check boxes to select a set of requests to operate upon... and the concept of a 'select all' box.
