### ISSUE TITLE
Request for a documentation on this project 

### ISSUE THREAD

**Issue by Anoopc444** [hyperledger/sawtooth-next-directory#371]
Hello Team,

Sorry for posting it as an issue as i didn't find any other way to communicate with the team.

Could you please provide all the BDD stories or any requirement document for this project?
I am a new babe in the block-chain area and i feel this will be a good exploratory project for me.
Any help on this would be highly appreciated.

**Comment by PatrickLammers** [comment]
Hi Anoopc444!  Welcome...  sorry this issue has languished.  I'm the new scrum master on this project and it has taken me a while to review the entire backlog of issues.  

Best documentation we have is on the [Wiki](https://github.com/hyperledger/sawtooth-next-directory/wiki) attached to this repo.  Best way to communicate with the team is via RocketChat (also on the wiki page)

Feel free to ping us there with questions and we look forward to your contributions!
