### ISSUE TITLE
Add High Level Architecture Document to the Project Sphinx Docs

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#376]
Produce a document using a diagramming tool:
https://www.draw.io/ 
https://graphviz.org/ 

Diagram the architecture of NEXT directory (ui, ledger_sync, providers, etc) calling out integrations, protocols, transformations, etc... 

Add the rendered document and its source file to /docs in the project.

Incorporate the rendered diagram into an architecture page to be built/hosted by Sphinx.

**Comment by PatrickLammers** [comment]
@dustinbarnes is this what you are doing?  Is this Sprint 10?

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
