### ISSUE TITLE
[User Story] Transaction Processor support for Approval on Behalf Of

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#379]
[User Story] | Transaction Processor support for Approval on Behalf Of
----------|----------
Epic Title | Hierarchical Approval , #118 
User Story Title | Transaction Processor support for Approval on Behalf Of
T-shirt size: S(mall), M(edium), L(arge) | M
Description | Processor accepts a proposal on behalf of list of IDs
Business Need (the why): | 
Details | 
Additional User Story | 
Acceptance Criteria/Tests |

**Comment by PatrickLammers** [comment]
tracked as a task on #1217 now
