### ISSUE TITLE
Short-Term Delegation

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#38]
Epic | Short-term delegation
----------|----------
Epic Title | Short-term delegation
Tasks | Define Short-term delegation #68 
User Story | As an approver in NEXT, I want to be able to designate a proxy who can review and approve/reject proposals for a defined period. 
Description | e.g. if manager will be going on vacation, allow them ability to assign for a limited time a specific person who can approve/disapprove.  Ensure assignee is allowed per policy.
Business Need (the why): | allows for no delays in access request in the event a NEXT user is out of office, on medical leave, vacation, etc.
Details | 
Additional User Story |
Acceptance Criteria/Tests | (see bulleted list below)   
Failure | designated proxy doesn't receive requests
Questions/Clarifications | 

- demo the UI for assigning a delegate. 
- Any pending requests already in the queue when delegation starts/stops shall be transferred to/from delegate. 
- Delegate request includes a message to delegate. 
- Delegate request shall trigger an email to recipient.  
- Approval/rejection of said request shall trigger an email notification to the requestor.
- during the duration of the delegation, any escalations that happen should still go to orginal owner manager (correct @chrisspanton )
- any place the role/pack owner name is referenced (ChatBot) during the delegation period, the delegate's name will be used.
- The granularity of the time interval shall be 'day' so transfers of proposals should begin/end at midnight (of which timezone?  Do we know the timezones of the two parties?)
- delegations shall be nestable or overlap-able -- multiple levels of delegation allowed.  We kinda need this if we are going to allow permanent delegations.
- originator of delegation can end it prematurely by resetting the end date -- but doesn't kick in until midnight
- The originator's people manager can modify the delegation (If I go on paternity leave and delegate to a peer, and then extend my leave by a week, I can call my boss and have them extend delegation)  This will trigger another accept email to the delegate.
- Anyone in the org is allowed to be delegated to and deal with approvals -- not limited to originators current org, his directs, etc...  
- if the delegate leaves the company all of their delegations shall revert back to originator (?  Does an email get triggered to someone here?)
- if the originator leaves the company during the time period should all ownership immediately revert to the manager?

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
