### ISSUE TITLE
[User Story]: NEXT app needs the ability to send email to users.

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#389]
[User Story] | Mail Daemon
----------|----------
Epic Title | 
User Story Title | Implement Mail Daemon
T-shirt size: S(mall), M(edium), L(arge) | 
User Story | 
Description | A daemon to send outbound emails, with relevant transports options.
Business Need (the why): |  There are several scenarios where NExT is expected to send an email to users...  forgotten password, weekly snapshot, etc.
Acceptance Criteria/Tests |  For this TASK, the acceptance criteria is that an email gets sent on the correct trigger -- this really isn't a story on its own.
Questions/Clarifications |  This is probably just a Task under one of the various "send an email" use cases...  _foundational work_ (shudder)

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
