### ISSUE TITLE
Permanent Delegation

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#39]
User Story | Permanent Delegation
----------|----------
Epic Title | Delegation
User Story | As a NEXT approver, I want to designate a permanent proxy who can review and approve/disapprove application/system access on my behalf.

**Acceptance Criteria/Tests** 
- Same basic functionality as Temp delegation but this has no end date. 
- Can be terminated if the orginater sets an end date.

**Comment by adamgering** [comment]
this was not on the sprint

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
