### ISSUE TITLE
[User Story] Implement email merge engine

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#390]
User Story | Implement email templates
----------|-----
Epic Title | Alerting
User Story Title | Implement email templates
T-shirt size: | 
Description | An email merge engine for generating emails from templates + data
Details | 
- Need templates for the following:
     - Delegation request 
     - snapshot (pending approvals, stale approvals, current delegations, items nearing expiration)
     - Single Access request 
            - person, org chart, message from requester
     - Aggregated access request
           - list of people by role (?)

**Acceptance Criteria/Tests** 
- correctly formatted HTML email messages sent to recipients

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
