### ISSUE TITLE
AWS IAM identity provider

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#391]
Task | [Spike] AWS IAM identity provider
----------|----------
Task Title | 
User Story | AWS IAM identity provider
Epic | 
T-shirt size default is S(mall) | 
Story Points - Fibonacci (1,2,3,5) | 
Description | Sync users and groups from IAM to rethink inbound queue and from outbound queue to IAM.
Business Need (the why): | 
Applications or Systems impacted | 
Dependencies | 
Assumptions |

**Comment by PatrickLammers** [comment]
Sounds like a lot of work...  Need to ask @chrisspanton if this should be in Release 1.0 of NEXT.

**Comment by PatrickLammers** [comment]
too broad to be actionable...  if the need arises for this in the future, we can create a series of better stories.
