### ISSUE TITLE
SX [Epic] Project Decomposition

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#406]
[Epic] | Project Decomposition
----------|----------
Epic Title | Project Decomposition
User Story Title | Project Decomposition
T-shirt size: S(mall), M(edium), L(arge) | L
Story Points - Fibonacci (1,2,3,5,8,13) | N/A
User Story | The project should be decomposed into user stories such that developers and stakeholders can prioritize and timeline the stories, developers have a practiced process for creating new stories, and developers are able to pick up stories to work on.
Description | 
Business Need (the why): | 
Details | Brainstorm the components that need to get built to achieve the vision of this project. Decompose those components into deliverable pieces and create a user story for those pieces. Mark that user story "SX [User Story] {Title}", assign them to the current sprint. Put them on the groomed board if they have no dependencies and can be worked on this sprint, otherwise leave them on the backlog board. Don't assign points until picked up.
Additional User Story |
Dependencies | 
Assumptions |

**Comment by PatrickLammers** [comment]
This is a story that just describe the Agile/Scrum project process.  Not really needed...
