### ISSUE TITLE
S5+ [User Story] Project Decomposition

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#411]
[User Story] | Project Decomposition
----------|----------
Epic Title | #406  Project Decomposition
User Story Title | Project Decomposition
T-shirt size: S(mall), M(edium), L(arge) | L
Story Points - Fibonacci (1,2,3,5,8,13) | 13
User Story | The project should be decomposed into user stories such that developers and stakeholders can prioritize and timeline the stories, developers have a practiced process for creating new stories, and developers are able to pick up stories to work on.
Description | 
Business Need (the why): | 
Details | Brainstorm the components that need to get built to achieve the vision of this project. Decompose those components into deliverable pieces and create a user story for those pieces. Mark that user story "SX [User Story] {Title}", assign them to the current sprint. Put them on the groomed board if they have no dependencies and can be worked on this sprint, otherwise leave them on the backlog board. Don't assign points until picked up.
Additional User Story |
Dependencies | 
Assumptions |

**Comment by kthblmfld** [comment]
To summarize what we accomplished this sprint: We carried out a number of decomposition stories as a team, breaking down hierarchical approval, capturing undocumented requirements (SMTP server/messaging, etc).  The assignees are contributors present in those meetings, thus our collective effort was 5 story points' work.
