### ISSUE TITLE
[User Story] Update project timeline

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#415]
There are a few legacy project timelines out there:
ProjectPlan_NEXTv1.3.docx
Next Identity (Alys roadmap).pptx

Produce an updated roadmap/timeline that captures new findings since ~Sept '18 to present.
Share the project source and rendered timeline with the project team and leadership for feedback, review, and re-prioritization

**Comment by PatrickLammers** [comment]
Work with Chris & Aly on revamping "Next Identity (Alys roadmap).pptx"
