### ISSUE TITLE
[User Story] Changes to role permissions should trigger reauth

### ISSUE THREAD

**Issue by chrisspanton** [hyperledger/sawtooth-next-directory#416]
[User Story] | Changes to a role's permissions should force an explicit reauth of all role members
----------|----------
Epic Title | (Epic NAME)
User Story Title | Immutable Roles
T-shirt size: S(mall), M(edium), L(arge) | L
Story Points - Fibonacci (1,2,3,5,8,13) | 
User Story | "Role entitlements should be immutably attached to the membership, any change to those entitlements (tasks) users should be re-authorized"
Description | From Nick Criss, new thinking around how roles/tasks/approval interface.
Business Need (the why): | Auditing
Details | Needs further thinking / whiteboarding with Nick
Additional User Story | linked
Acceptance Criteria/Tests | The list of tests or criteria to be used to validate the story has been completed. May still need UAT or SIT / integration testing with other stories.
Failure | if any, fold in negative tests
Definition of Done | e.g.Passes all regression tests, Passes testing per acceptance criteria, Approved by UI team, Able to show feature in demo                                                                                                    
UX/UI Details and/or mockups | if UI change, a mockup or description of what to change, attach image/file
Applications or Systems impacted | upstream/downstream applications/systems
Dependencies | non story dependencies
Assumptions | if any
Performance Considerations | Will the work performed as part of this story impact system performance. If there is potential for a performance hit, where would you expect it to manifest in the system.
Security Considerations | E.g., does this story involve working with Personal Identifying Information (PII)? Note any such security sensitive aspects.
QA Considerations | what might be hard to test or test setup criteria
Acrhitectural/System or Component Impacts | if we're adding something new or significantly changing architecture flag for architect review
Reverse Engineering Required | to document areas not known well by dev team
Questions/Clarifications | Create new issue (add label: question) in this repo and link to this issue

**Comment by PatrickLammers** [comment]
I get that we should do reauth in this scenario to prevent "permissions creep" for role members.  Tied to #431.  

- Would this require both the member's manager and the role owner or just the role owner?
- Would the role members get a notification somehow that permissions have changed?
- If permissions get taken away, do we still need to reauth or only if permissions get expanded?
- if permissions get removed, should we still notify all role members so they understand why something stopped working?

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
