### ISSUE TITLE
S5 [User Story] Documentation

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#420]
[User Story] | Documentation
----------|----------
Epic Title | #123 
User Story Title | Documentation
T-shirt size: S(mall), M(edium), L(arge) | L
Story Points - Fibonacci (1,2,3,5,8,13) | 8
User Story | Sphinx-based documentation
Description | Add content to the sphinx documentation. Anything at all, get started.

- [x] Update rebase documentation in the wiki
- [x] Add how-to Sphinx documentation to the wiki
- [x] Customize, build introductory Sphinx pages in /docs
- [x] Integrate readthedocs.io with github
- [x] Add Docs build health badge to README

**Comment by kthblmfld** [comment]
[ ] Update rebase documentation in the wiki

**Comment by kthblmfld** [comment]
Sphinx docs are compiling and deploying on build. They are integrated with the webhook on Github.
