### ISSUE TITLE
[User Story] Good Bad and Ugly Proposal Tests

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#421]
[User Story] | Good Bad and Ugly Proposal Tests
----------|----------
Epic Title | #32 
User Story Title | Good Bad and Ugly Proposal Tests
T-shirt size: S(mall), M(edium), L(arge) | M
Story Points - Fibonacci (1,2,3,5,8,13) | 2
User Story | 
Description | Proposals should have advanced test coverage, especially validation and failure states, prior processor validation refactoring into message classes; a dependency to changing validation functionality (#379)
Business Need (the why): | 
Details | 
Additional User Story | 
Acceptance Criteria/Tests | 
Failure | 
Definition of Done |                                                                                       
Applications or Systems impacted | 
Dependencies |  #379
Assumptions | 
QA Considerations | 
Reverse Engineering Required |
Questions/Clarifications |

**Comment by PatrickLammers** [comment]
@adamgering This is just a reminder to increase out test coverage across the backend, yes?  Why linked to #379?

**Comment by adamgering** [comment]
Proposal test coverage is and was a pre-requisite before new proposal features (#379) could be implemented. It was a separate story because it was sprint scheduled and pointed separately.
