### ISSUE TITLE
S8 [User Story] API Endpoint Get a User's Roles (groups)

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#424]
[User Story] | Hierarchical approval
----------|----------
Epic Title | Hierarchical approval #118
User Story Title | Api Endpoint Get a User's Roles
T-shirt size: S(mall), M(edium), L(arge) | S
Story Points - Fibonacci (1,2,3,5,8,13) | 3
User Story | [Value Statement] "As a user of NEXT, I want to be able to get the roles associated with a user"
Description | Implement capability to browse a user's Roles
Business Need (the why): | Having access to a user's Roles will help with implementing hierarchical approval for a user.
Details | Create API endpoints for getting a user's Roles. Add a simple UI page to display the hierarchy. 
Additional User Story | linked
Acceptance Criteria/Tests | The list of tests or criteria to be used to validate the story has been completed. May still need UAT or SIT / integration testing with other stories.
Failure | if any, fold in negative tests
Definition of Done | e.g.Passes all regression tests, Passes testing per acceptance criteria, Approved by UI team, Able to show feature in demo                                                                                                    
Architectural/System or Component Impacts | This will be in Sanic and may utilize already existing apis

**Comment by kthblmfld** [comment]
It looks like some of the descriptions here were copied over from a story about looking up direct reports. I am assuming this is an endpoint for getRoles(userId).

**Comment by kthblmfld** [comment]
Taking myself off this task as there is currently misunderstanding of the end value of this feature.

**Comment by nadiabahrami** [comment]
I have confirmed that both Azure and AD are providing what groups a user belongs to on the memberOf field.  Closing this ticket as complete
