### ISSUE TITLE
[SPIKE] Look into use and how to implement GRAPHQL

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#429]
[User Story] | GRAPH QL
----------|----------
Epic Title |
User Story Title | Look into use and how to implement GRAPH QL
T-shirt size: S(mall), M(edium), L(arge) | S
Story Points - Fibonacci (1,2,3,5,8,13) | 3
User Story | [Value Statement] "As a developer I would like to know which tech to use on the project that are helpful in achieving the project in it's best form.
Description | This is a SPIKE to look into how to implement GRAPHQL and what the benefits are.  A plan of action of whether to do this or not, documentation, and tickets should be generated at the end of this spike.
Business Need (the why): | 
Acceptance Criteria/Tests | There is a direct plan of action on whether to implement GRAPH QL or not and how to do so(Tickets have been written, architecture documents drawn, etc)

**Comment by PatrickLammers** [comment]
This doesn't seem to be getting traction....  I'm sure it will be reactivated if this is truly a concern
