### ISSUE TITLE
 Improve naming of User fields

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#43]
[User Story] | Improve naming of User fields
----------|----------
Epic Title | Developer-friendly codebase
User Story Title | Improve naming of User fields
T-shirt size: S(mall), M(edium), L(arge) | S
Story Points - Fibonacci (1,2,3,5,8,13) | 3
User Story | "As a developer, I want to understand the purpose of user object attributes"
Details | Rename fields [user, user_id, user_name] to [user_name, user_key, user_logon], respectively
Acceptance Criteria/Tests | The fields of User have been updated per the change described previously, and the changes do not cause any existing tests to fail

**Comment by mtn217** [comment]
Decided to not update the fields on the UI side because the UI will be migrated to React and any variable names I change on the UI will be later be changed. Updating Swagger API documentation now.

**Comment by adamgering** [comment]
was not in sprint 3, is in backlog

**Comment by adamgering** [comment]
Closing, address later.
