### ISSUE TITLE
S5 [User Story] Publish Documentation

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#445]
User Story | Publish Documentation
----------|----------
Epic Title | #123 
User Story Title | Publish Documentation
T-shirt size: S(mall), M(edium), L(arge) | M
Story Points - Fibonacci (1,2,3,5,8,13) | 3
User Story | Documentation can be read by anyone and is up-to-date.
Description | Publish documentation to ReadTheDocs (readthedocs.org)
Business Need (the why): | 
Details | 
Additional User Story |                                                                                           
Dependencies | 
Assumptions | 
Questions/Clarifications |

**Comment by kthblmfld** [comment]
The documentation is now building in automation, linked to the repo github, badged on README.
