### ISSUE TITLE
[User Story][UI] Add loading interstitials

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#458]
User Story | Add loading interstitials
----------|----------
Epic Title | Multi-party approval [#76](https://github.com/hyperledger/sawtooth-next-directory/issues/76)
User Story Title | Add loading interstitials
T-shirt size: S(mall), M(edium), L(arge) | M
Story Points - Fibonacci (1,2,3,5,8,13) | 3
User Story | As a user, I want the UI to display a progress loader while waiting for page content to populate.
Description | Transitioning between UI screens is currently jarring. Add reusable progress loaders that displays when a user navigates between routes.
Business Need (the why): | A client that integrates with the API facilitates demos and showcases the new UI design.
Details | Tasks: [#294](https://github.com/hyperledger/sawtooth-next-directory/issues/294) [#297](https://github.com/hyperledger/sawtooth-next-directory/issues/297)

**Comment by PatrickLammers** [comment]
Do we need this for the demo?

**Comment by pgobin** [comment]
@PatrickLammers Nope. Closing as per the implication of our email discussion.
