### ISSUE TITLE
Update lint shell script such that it reports when a target directory is absent

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#463]
In bin/run_lint.sh are a list of directories PyLint runs against when 'bin/build -l' is executed. 

The first list is for cli arg filtering and the second is for default execution.

(Try to) Move the paths into a list to be referenced by both. 

The args already has a check for the provided option. However, in the second block: When a directory in the list is missing (ie a code refactoring/rename happens), this script fails with non-obvious errors. 

Check for the existence of the directories before linting them. Fail with an obvious error when any are missing.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
