### ISSUE TITLE
[Bug] Integration tests were not updated to reflect change in proposal signing requirements

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#47]
Integration tests were not updated to reflect change in proposal signing requirements done in PR # 18

`processor/rbac_processor/role/common.py`
`def validate_role_rel_proposal`

**Comment by kthblmfld** [comment]
Moving this to done as these updates were merged and tests should now pass.

**Comment by adamgering** [comment]
Integration tests are passing.
