### ISSUE TITLE
remove lint ignore R0901

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#486]
[User Story] | Remove lint ignore for R0901
----------|----------
User Story Title | Remove lint ignore for R0901
T-shirt size: S(mall), M(edium), L(arge) | S
User Story | "As a developer on an open source project I want, clean code that adheres to python code-styles for easier development
Description | Remove the ignore for R0901 - too-many-ancestors from setup.cfg.  If this seems impossible discuss with team and come to decision on whether to keep ignore or not.
Acceptance Criteria/Tests | The error is removed from the ignore in setup.cfg and code is fixed so linter passes
Definition of Done | passes linter

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
