### ISSUE TITLE
Bi-Directional AAD Provider Integration (Cloud)

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#49]
[User Story]  | AAD Integration
----------|----------
Epic Title | Active Directory Integration ([https://github.com/hyperledger/sawtooth-next-directory/issues/35])
User Story Title | Graph API Provider
T-shirt size: | It's HUUUGEE!
Description | Build API integration for Azure AD (Cloud). Collaboration with Microsoft team
Business Need (the why): | ensure Azure AD functionality for NEXT
Definition of Done | Bi-directional data sync with conflict resolution. Integration will resolve any user conflicts.

**Comment by PatrickLammers** [comment]
no AAD for prod parallel

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
