### ISSUE TITLE
Data Storage and Schema

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#516]
Epic | Data Storage and Schema
----------|----------
Epic Title | Data Storage
T-shirt size default is L(arge) | L
Description | Determine how and where data will be stored, how it will be addressed, how it will be modeled, how it will be queried, how it will be replicated, how it will be persisted, how it will be backed up.
Details | Sawtooth provides a replicated and immutable key-value data store with transactional history where key is a 35-byte address and value is an opaque string. This is effectively a NOSQL data store, the addressing scheme is up to the application to invent. RethinkDB provides a document database with a streaming changelog API.

**Comment by PatrickLammers** [comment]
This isn't an Epic since it isn't being used to wrap other stories...  remove the label and title.  Probably should just kill this story...  I think #74 captures the open questions

**Comment by PatrickLammers** [comment]
pretty sure this one is taken care of now
