### ISSUE TITLE
Packs (was "Virtual Roles")

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#529]
Epic | Packs
----------|----------
Epic Title | Packs
T-shirt size default is L(arge) | XL (cause it's an Epic after all)
Business Need (the why): | NEXT should have the ability to create/aggregate bundles of roles to accurately reflect real-world usage.  
User Scenarios | #85

**Comment by kthblmfld** [comment]
I believe we refer to this data structure as "Pack" now.

**Comment by PatrickLammers** [comment]
Not migrated to new tmobile/sawtooth-next-directory repo 
Just closing this here since we only have one story left to complete and it has been migrated.
