### ISSUE TITLE
[User Story] Transaction Processor Hot Reloading

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#541]
[User Story] | Transaction Processor Hot Reloading
----------|----------
Epic Title | #32 
User Story Title | Transaction Processor Hot Reloading
T-shirt size: S(mall), M(edium), L(arge) | M
User Story | The transaction processor should monitor for file changes and pull in those changes without requiring the docker container be restarted.
Description | 
Business Need (the why): | 
Details | 
Additional User Story |
Dependencies | 
Assumptions | 
Questions/Clarifications |

**Comment by adamgering** [comment]
Ready for review, but I'm waiting on the previous two PRs to be accepted before I submit a third.

**Comment by adamgering** [comment]
finished, but will continue to test before submitting PR, may refactor

**Comment by PatrickLammers** [comment]
@adamgering This story seems to be bouncing between 'needs review' and the backlog.  What is the current state?

What functionality would this give us?  Does this let up push code changes to the NEXT system without downtime?  What "file changes" specifically get monitored here -- just config files?  Thanks!

**Comment by PatrickLammers** [comment]
I *think* this just means our Next system monitors or periodically re-reads config files and applies changes...  This way we wouldn't need to stop and restart it to force it to re-read.  But maybe I'm wrong...  hopefully we can add this for PP

**Comment by PatrickLammers** [comment]
seems like we don't need this anymore...
