### ISSUE TITLE
[User Story] Data Model - Data Queried by User ID

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#551]
[User Story] | Data Model - Data Queried by User ID
----------|----------
Epic Title | 
User Story Title | Data Model - Data Queried by User ID
T-shirt size: S(mall), M(edium), L(arge) | M
User Story | Data Model - Data Queried by User ID
Description | Data that needs to be queried by User ID
Details | 
Additional User Story | 
Dependencies | 
Assumptions | 
Questions/Clarifications |

**Comment by PatrickLammers** [comment]
pretty sure we have this one too.
