### ISSUE TITLE
[User Story] Inbound/Outbound AAD Tests

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#563]
User Story | Outbound AAD Tests
----------|----------
User Story Title | Outbound AAD Tests
T-shirt size default is S(mall) | m 
Story Points - Fibonacci (1,2,3,5) | 5
Description | Create a daemon process to get changes to users in a configured Azure AD provider and put them in queue_inbound in rethink.

**Comment by PatrickLammers** [comment]
Is this work to create unit tests or is describing validation of data?  The description above makes me think it's the latter...

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
