### ISSUE TITLE
Configure logging in one place

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#579]
All throughout the codebase are logger imports and custom configurations for particular levels. In the actual logs that make their way out are a few discrepancies in their formats (some have date/time/module, others don't.

This needs to be consolidated up into one global configuration and given one standard format. 

Configure in env?

**Comment by PatrickLammers** [comment]
let's get our logging story straight before going to PP.

**Comment by Nonj** [comment]
Here is my list of what I'm going to do for this story:
     * Logs everything into one log file (Local)
     * Standardize the logging format
     * Not solving for multi-node
