### ISSUE TITLE
S2 [UX Design] End State View (UX and Visual Language)- Finalize the design concept and visuals

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#58]

**Comment by agoldingay** [comment]
will edit further .

**Comment by agoldingay** [comment]
Preliminary UI was reviewed 9/7 and 9/11. Additional grooming will be spent to add within each appropriate user stories.

**Comment by chimpuz** [comment]
Final presentation for the visual design kit is scheduled for Thu, Sep 20.

**Comment by chimpuz** [comment]
Final presentation was done earlier today. The artifacts are uploaded at: https://drive.google.com/drive/u/0/folders/1JoEfd3tmAU4rShpmApg0ZJYteswaIDos

**Comment by chrisspanton** [comment]
Love it!
