### ISSUE TITLE
Enable debugging in development

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#581]
Come up with a way to leverage pdb to add breakpoints to the code while troubleshooting and connect to them for inspection/evaluation in the IDE. 

Reason: We are spending unnecessary time trying to debug using print/log statements, and some cases cannot be solved. Having the ability to debug would improve productivity by reducing troubleshooting time in startup, log, shutdown, fix loop

**Comment by PatrickLammers** [comment]
@kthblmfld seems like an unlikely thing to put in a story.  Have we tackled any of this yet?

**Comment by PatrickLammers** [comment]
seems like the dev team will raise this again if it is truly an issue...
