### ISSUE TITLE
Scale up/out RethinkDb

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#586]
Since day 1, we have been seeing warnings coming out of RethinkDb about it using swap space:

rbac-rethink | warn: Some RethinkDB data on this server has been placed into swap memory. This may impact performance.

We haven't put much load on it yet. 

Research and implement the best means of scaling it to handle the expected data load (more memory? More nodes?)

Related to story #729 perhaps?

**Comment by PatrickLammers** [comment]
revisit this if/when we start to see problems with ReThink
