### ISSUE TITLE
[BUG] Handle missing/invalid data_type field in AAD in/outbound queue

### ISSUE THREAD

**Issue by jbobo** [hyperledger/sawtooth-next-directory#587]
Task | Handle missing/invalid data_type field in AAD in/outbound queue
----------|----------
Task Title | Handle missing/invalid data_type field in AAD in/outbound queue
Description | An in/outbound queue entry with a missing or invalid data_type field value and provider_id of "azure" will break the AAD delta outbound sync daemon. Malformed queue entries should be flaggedm moved to the changelog, and deleted from the queue.
Applications or Systems impacted | AAD in/outbound delta sync daemons.

**Comment by PatrickLammers** [comment]
Is this a duplicate of #662??  Why is this a bug and not just missing code?

**Comment by PatrickLammers** [comment]
no AAD for prod parallel

**Comment by jbobo** [comment]
This is handled by #662 so we're closing this ticket.
