### ISSUE TITLE
[User Story] Configuration Helper Class

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#589]
[User Story] | Configuration Helper Class
----------|----------
Epic Title | 
User Story Title | Configuration Helper Class
T-shirt size: SML | M
Story Points - Fibonacci (1,2,3,5,8,13) | 2
User Story | Configuration Helper Class
Description | A common configuration helper class that allows services (daemons) to specify the environmental variables they expect require, along with defaults values, command line flags, and helper text.
Business Need (the why): | 
Details | 
Additional User Story | #this story prompted by #533 
Dependencies | 
Assumptions |

**Comment by PatrickLammers** [comment]
closing for now
