### ISSUE TITLE
S1 [Bug] Stopping and restarting Application results in unexpected application behavior

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#61]
Stopping and restarting the application via `docker` results in unexpected application behavior.

`docker-compose up`

Create some users.

`docker-compose stop`
`docker-compose up`

Result: ledger-sync_1 failures.
Can log in but can't sign up or create new users.

Works only by taking the app down and then up.

`docker-compose down`
`docker-compose up`

However, that will remove all data and start from scratch.

**Comment by agoldingay** [comment]
Closing per Adam.
