### ISSUE TITLE
[Spike] Investigate adding a Message Broker to NEXT in place of RethinkDb queue tables

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#614]
We used queue tables in RethinkDb to move quickly during the hackathon with Microsoft. These tables are being used to essentially carry out Pub/Sub in NEXT. This is the behavior of a message broker. 

Sawtooth uses zeroMq for its messaging. A popular message broker for OSS projects is RabbitMq. Using a message broker simplifies such matters as bulk/time-offset replay, failover into backout queues, etc. 

There is a library for rethinkDb called repubsub (https://github.com/rethinkdb/example-pubsub/tree/master/python) although it is a bit dated (apparently it once integrated well with RabbitMq).

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
