### ISSUE TITLE
[User Story] NEXT image sync

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#624]
[User Story] | NEXT image sync
----------|----------
Epic Title | #623 Readme update
User Story Title | NEXT image sync
T-shirt size: S(mall), M(edium), L(arge) | M
Story Points - Fibonacci (1,2,3,5,8,13) | TBD
User Story | I want to maintain the NEXT image such that the most current image is always being projected on the repo within Readme
Description | A short description 
Business Need (the why): | from epic, if needed
Details | All the details needed to accomplish the story. Tasks - can be linked
Additional User Story | linked
Acceptance Criteria/Tests | The list of tests or criteria to be used to validate the story has been completed. May still need UAT or SIT / integration testing with other stories.
Failure | if any, fold in negative tests
Definition of Done | e.g.Passes all regression tests, Passes testing per acceptance criteria, Approved by UI team, Able to show feature in demo                                                                                                    
UX/UI Details and/or mockups | if UI change, a mockup or description of what to change, attach image/file
Applications or Systems impacted | upstream/downstream applications/systems
Dependencies | non story dependencies
Assumptions | if any
Performance Considerations | Will the work performed as part of this story impact system performance. If there is potential for a performance hit, where would you expect it to manifest in the system.
Security Considerations | E.g., does this story involve working with Personal Identifying Information (PII)? Note any such security sensitive aspects.
QA Considerations | what might be hard to test or test setup criteria
Acrhitectural/System or Component Impacts | if we're adding something new or significantly changing architecture flag for architect review
Reverse Engineering Required | to document areas not known well by dev team
Questions/Clarifications | Non will further complete this issue with Chris' help.

**Comment by PatrickLammers** [comment]
@Nonj Not sure what this story is describing...  Is there some automated way of grabbing a screenshot of a target page in the UI and saving to our GIT repo so that the readme always reflects the current build?  Seems like a good way to get out of sync with the surrounding text if we make dramatic changes.   Is this a "standard" way of maintaining the readme?  Safer to simply schedule a periodic touch up the content?

Very low priority to me...  change my mind!

**Comment by PatrickLammers** [comment]
closing with migration.  If we decide we need this, we will root around and find it again.
