### ISSUE TITLE
Define Approval Configuration

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#64]
Epic | Approval Configuration
----------|----------
Epic Title | Configuration
T-shirt size  | L
Description | Define approval types that will trigger logic in delivering multi-approval, hierarchical and batch approval functionality
Business Need (the why): | Allows for compliance policy as well as ease of large approval sets
Stakeholders | 
Details | All the details needed to accomplish the story. Tasks - can be linked
User Scenarios | Multi-party approval #27, Hierarchical approval #32  and batch approval #37 
Acceptance Criteria/Tests | _The list of tests or criteria to be used to validate the story has been completed. May still need UAT or SIT / integration testing with other stories._

**Comment by yunhangc** [comment]
To approach this issue, we need:

1. list all proposal types: add/remove role member,  add/remove role admin,  add/remove task admin, update user manager etc
2. for each type of proposal, list all possible PERSONAS that could be the approvers. ex. for role, we may need role owner/admin and the employee's manager  
3. enumerate those possible personas, and for each case, code how to fetch those persona's id from the payload. 

with those, we can put configurations like this on the database/chain. The config json should handle multi-party approval, hierarchical approval

{  
   "type":"ADD_ROLE_MEMBER",
   "approvers":[  
      {  
         "persona":"ROLE_OWNER",
         "hierarchical":false
      },
      {  
         "persona":"MANAGER",
         "hierarchical":true
      }
   ]
}

**Comment by mtn217** [comment]
Here's the list of proposal types currently implemented on the platform:
```
    ADD_ROLE_TASKS 
    ADD_ROLE_MEMBERS 
    ADD_ROLE_OWNERS 
    ADD_ROLE_ADMINS
    REMOVE_ROLE_TASKS 
    REMOVE_ROLE_MEMBERS 
    REMOVE_ROLE_OWNERS 
    REMOVE_ROLE_ADMINS
    ADD_TASK_OWNERS 
    ADD_TASK_ADMINS 
    REMOVE_TASK_OWNERS 
    REMOVE_TASK_ADMINS 
    UPDATE_USER_MANAGER 
```

**Comment by agoldingay** [comment]
i'll schedule a meeting so we can discuss in depth

**Comment by agoldingay** [comment]
Team, please add your comments so we can get alignment on Richard's recommendation. Then we can move forward. Thanks!

**Comment by yunhangc** [comment]
on the approval / confirmation side:

1. we will keep track the approval inside the proposal object. on the event of another approval, we will run the list against the configuration to check whether it satisfies the condition, if so, we close the proposal.
2.In the case of a rejection, we will close the proposal right away.

At implementation, we may need to pay attention to the situation where one person wears multiple hats. ex. one individual is both the requester's manager and the owner of the group

**Comment by adamgering** [comment]
Looks like a good start. First step would be to define the approval requirement for each task, as per T-Mobile's requirements, and then go from there.

**Comment by kthblmfld** [comment]
A few thoughts:
The change should include tests that both affirm the changes and try to break them.
Until we have well-defined requirements or architecture docs to compare these changes to, my sign off is an automatic "Yes". The sooner we can build out the feature and get it in front of Nick & Chris as a demo, the better. We can iterate on their feedback, using it to build fine-grained tasks.

**Comment by yunhangc** [comment]
@kthblmfld I would agree with you. trying to get a bare bone built quickly 

@adamgering my understanding is that this would have a broader application than just for T-Mobile. But we can start from T-Mobile's scenario for sure.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
