### ISSUE TITLE
Advanced Authentication

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#65]
Epic | Advanced Authentication
----------|----------
Epic Title | Advance Authentication issues
T-shirt size default is L(arge) | XL (cause it's an Epic)
Description | allows for users to self-serve by allowing themselves to reset password and retrieve their  username should these be lost or forgotten
Business Need (the why): | allows self-service without IT support help
User Scenarios | User password reset #66 , User Retrieves their Username #67 , Handling of Failed Logins #75

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
