### ISSUE TITLE
Speed up inbound from AAD

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#654]
User Story | AAD - Use offset to decrease inbound time
----------|----------
User Story Title | Use Offset to decrease inbound time
T-shirt size default is S(mall) | s
Story Points - Fibonacci (1,2,3,5) | 3
Description | Currently the inbound queue goes through all of the possible events without using an offset to stop going through them.  We would like to us the offset so that the inbound checks will be faster at processing.

**Comment by PatrickLammers** [comment]
is there a corresponding story for speeding up AD inbound?

**Comment by PatrickLammers** [comment]
marking for PP on the assumption that it needs to be sped up.  If someone knows otherwise, speak up!

**Comment by PatrickLammers** [comment]
No AAD for prod parallel

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
