### ISSUE TITLE
[User Story] Docker policy to bring back provider daemons if they go down

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#656]
User Story | Docker Policy to bring back provider daemons if they go down
----------|----------
User Story Title | Docker Policy to bring back provider daemons if they go down
T-shirt size default is S(mall) | s
Story Points - Fibonacci (1,2,3,5) | 3
Description |  If  a provider daemon goes down we need it to automatically restart.  This is to prevent outages in process flow.  be sure to log the restart so we can monitor it.

**Comment by satkeeva** [comment]
Connected to "Docker Restart Policy" ticket.
