### ISSUE TITLE
[User Story] User Password Reset

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#66]
User Story | Password Reset
----------|----------
Epic Title | Advance Authentication #65 
User Story Title | User Password Reset
T-shirt size: S(mall), M(edium), L(arge) | 
User Story | As an authorized user with valid credentials, I want to reset my NEXT password on my own without assistance from an IT person
Description | Allows a user to reset password on their own.
Acceptance Criteria/Tests | If I have a valid account on NEXT and I'm able to log in, I can navigate to a UI that allows me to change my password. Passwords are hidden as they are entered.  Password rules are enforced.                                                                    
UX/UI Details and/or mockups | for Moonraft guys to detail.

**Comment by adamgering** [comment]
Feature implementation is dependent upon email templates and SMTP connector.

**Comment by PatrickLammers** [comment]
Not sure what email has to do with this story.  This isn't forgotten password, this is navigating to the 'my acct' section of the UI and changing my password.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
