### ISSUE TITLE
AAD - Validator Tests

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#661]
User Story | AAD - Validator Tests
----------|----------
User Story Title | AAD - Validator Tests
T-shirt size default is S(mall) | s
Story Points - Fibonacci (1,2,3,5) | 3
Description |  AAD - Testing Validators for payload in and outbound checks -- pair with story #662

**Comment by PatrickLammers** [comment]
no AAD for prod parallel

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
