### ISSUE TITLE
[User Story] AAD - Set up validators for in and outbound payloads

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#662]
User Story | AAD - Set up validators for in and outbound payloads
----------|----------
User Story Title | AAD - Set up validators for in and outbound payloads - pair with #661 
T-shirt size | s
Story Points - Fibonacci (1,2,3,5) | 3
Description |  AAD - Set up Validators for in and outbound payloads for Azure.  This means testing what is necessary for creating and updating a user and creating blocks for submissions that do not contain all the necessary fields, Or fields that are unnecessary.

**Comment by PatrickLammers** [comment]
@nadiabahrami I *think* this story is trying to prevent us from writing incorrect or incomplete data to Azure, right?  (that would be "outboud" from Next perspective...)  But why would need to validate the inbound from Azure?  Are there incomplete/incorrect records in AAD already?

Would we simply block the read/write when we encounter an issue?  Would we warn the user and prompt them to make changes?  Would we attempt to create the missing bits automatically?

**Comment by PatrickLammers** [comment]
no AAD for prod parallel

**Comment by PatrickLammers** [comment]
see also #587

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
