### ISSUE TITLE
[User Story] User Retrieves their Username

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#67]
[User Story] | User Retrieves Username
----------|----------
Epic Title | Advance Authentication #65 
User Story Title | User Retrieves their Username
T-shirt size: SML | 
User Story | An an authorized user with a bad memory, I want to retrieve my NEXT username on my own without assistance from a person. 
Acceptance Criteria/Tests | The user is prompted for some information that only they would know (or email address used within Next) Once info is provided, the system coughs up the username (or emails username to the registered email address).  If the info provided doesn't match anything, we shouldn't inform the user.                                                                                          
UX/UI Details and/or mockups | Looks like we need UI on the sign in page.  Have to add a 'forgot username' button.  It should then prompt me for my registered email address?
Questions/Clarifications |

**Comment by adamgering** [comment]
An alternative to this story would be a feature to simply allow a user to log in via either their username or their email. Or that may be a configurable option and would need to support both.

**Comment by PatrickLammers** [comment]
I like Adam's suggestion on this one...  so main screen maybe just needs to say "username or email" and we accept either one. ??

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
