### ISSUE TITLE
S7 [User Story] Add/test json/metadata support to protobufs

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#670]
[User Story] | Add/test json/metadata support to protobufs
----------|----------
Epic Title | #333 
User Story Title | Add/test json/metadata support to protobufs
T-shirt size: S(mall), M(edium), L(arge) | S
Story Points - Fibonacci (1,2,3,5,8,13) | 1
User Story | Add and test json support to the protobufs
Questions/Clarifications |

**Comment by adamgering** [comment]
This is more likely 2-3 pts, looking at using child protobuf messages.
Other options are protobuf Map type or CBOR.

**Comment by kthblmfld** [comment]
Adam is considering moving excess metadata fields into RethinkDb at this time (to reduce data loss, track additional optional data). This will likely be the solution to this story, and he will close this story once that becomes the case.

**Comment by adamgering** [comment]
Added metadata table to store off-chain metadata.

**Comment by adamgering** [comment]
resolved in PR #818
