### ISSUE TITLE
[User Story] Add Role-to-Role relationship

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#674]
[User Story] | Add Role-to-Role relationship
----------|----------
Epic Title | #333 
User Story Title | Add Role-to-Role relationship
T-shirt size: S(mall), M(edium), L(arge) | S
Story Points - Fibonacci (1,2,3,5,8,13) | 2
User Story | Add Role-to-Role relationship
Description | 
Business Need (the why): | AD supports it, we need to track reality even if we decide to disallow by configuration.
Details | 
Additional User Story | 
Acceptance Criteria/Tests | 
Dependencies | 
Assumptions | 
Questions/Clarifications |

**Comment by PatrickLammers** [comment]
@chrisspanton What T-Mo user functionality is enabled by this?  I agree that we need to support this if AD does but knowing if there is a T-Mo use case it would help us determine priority

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
