### ISSUE TITLE
[User Story] Store multiple user proposal actions on a proposal

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#675]
User Story | Store multiple user proposal actions on a proposal
----------|----------
Epic Title | #27 
User Story | Store multiple user proposal actions on a proposal.  Presently we are able to store ONE proposal action (confirm or reject) on a proposal record. In order to achieve multi-party approval, we need to store {N} actions (confirmations or rejections) on a proposal record.  This story proposes a change in the schema from one to many.
T-shirt size: S(mall), M(edium), L(arge) | M

**Comment by PatrickLammers** [comment]
@adamgering I added your comments from email to the above user story comment.  Having a proposal with multiple owners and multiple actions would mean that they are associated based on order?  So first owner maps to first response?

**Comment by PatrickLammers** [comment]
per conversation with George, this is an implementation detail on story #862.  close this one
