### ISSUE TITLE
[User Story] Add proposal assignment to data model

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#676]
[User Story] | Add proposal assignment to data model
----------|----------
Epic Title | #32 
User Story Title | Add proposal assignment to data model. Create a user_proposal record. 
T-shirt size: S(mall), M(edium), L(arge) | M
User Story | Add proposal assignment to data model.  This data will indicate the 'owner' of the next action on this proposal and can be used to retrieve all 'owned' proposals to populate the UI for building lists of requests that need action.  
Accceptance Criteria | Add to the addressing scheme a new address with an associated protobuf called "user_proposal".   Demonstrate that the UI only receives the list of proposals for the current user instead of receiving ALL open proposals (and then needs to filter them down to appropriate list)

**Comment by PatrickLammers** [comment]
Not sure of the status of this one...  clearly not in progress for current sprint though.

**Comment by PatrickLammers** [comment]
revisit this one if perf becomes an issue.  Do we have business logic in the UI layer here?

**Comment by PatrickLammers** [comment]
will revisit this if design says it it needed.
