### ISSUE TITLE
[User Story] Migrate API reads to new data model

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#677]
[User Story] | Migrate API reads to new data model
----------|----------
Epic Title | #32 
User Story Title | Migrate API reads to new data model
T-shirt size: S(mall), M(edium), L(arge) | L
User Story | Migrate API reads to new data model
Description | query the rethink state table, to accommodate the underlying data model that changed
Business Need (the why): | the existing end point is looking at obsolete tables. It re-points to the new tables
Details | Version the APIs, so there can be distinction between the old API and the new API. e.g. '/v1' or '/v2'
Additional User Story |
Acceptance Criteria/Tests | For purposes of demoing, we will utilize postman. Show a before and after state. 
Questions/Clarifications | Refer to Adam as the SME for this particular user story.

**Comment by PatrickLammers** [comment]
Nadia suggests killing this story and bringing in all the existing API stories that refer to this.

**Comment by PatrickLammers** [comment]
@adamgering Is this one done?
