### ISSUE TITLE
[Task] Define short-term delegation

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#68]
Task | Define short-term delegation
----------|----------
Task Title | Define short-term delegation
User Story | Short-Term Delegation #38 
Epic | link associated Epic, if applicable
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | ensure the sum of the story points do not exceed the User Story
Description | Define short-term delegation in days, weeks, or months
Business Need (the why): | how does this task tie into the user story
Applications or Systems impacted | 
Dependencies | if certain tasks must be done in a certain order, note here
Assumptions | _if any_

**Comment by adamgering** [comment]
this was not on the sprint

**Comment by PatrickLammers** [comment]
seems like yet another 'story to write a story' -- we will track the functionality of short term delegation in #38
