### ISSUE TITLE
Create RethinkDb tables before starting Docker containers that use them 

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#681]
The RethinkDb tables are being created within ledger_sync for no justifiable reason. When other containers start up before ledger_sync, workarounds need to be put in the code to ensure the apps wait for the tables to appear.

Instead, the database setup should happen before the dependent containers are brought up at all. This ensures now special treatment needs to be written into connectors that works around an existing design flaw.

**Comment by jbobo** [comment]
https://docs.docker.com/compose/startup-order/
>You can control the order of service startup and shutdown with the depends_on option. Compose >always starts and stops containers in dependency order, where dependencies are determined by >depends_on, links, volumes_from, and network_mode: "service:...".
>
>However, for startup Compose does not wait until a container is “ready” (whatever that means for >your particular application) - only until it’s running. There’s a good reason for this.
>
>The problem of waiting for a database (for example) to be ready is really just a subset of a much >larger problem of distributed systems. In production, your database could become unavailable or >move hosts at any time. Your application needs to be resilient to these types of failures.

>To handle this, design your application to attempt to re-establish a connection to the database after a >failure. If the application retries the connection, it can eventually connect to the database.
>
>The best solution is to perform this check in your application code, both at startup and whenever a >connection is lost for any reason. However, if you don’t need this level of resilience, you can work >around the problem with a wrapper script:

So it looks like we should just continue with the health-checks we have in our code and refactor them down the road to be more resilient. There might even be a library we could use to keep our code from looking too hacky. I think for the time being we should probably close this ticket.
