### ISSUE TITLE
Rename requirement.local.txt

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#682]
requirement.local.txt (Should be requirements.local.txt) appears to be enabling some new contributor to run something. However, the dependencies described within are in the first 2 lines of requirements.txt. 

We had some discussion about this file, and its existence has yet to prove any value at this time, yet its deletion is disputed. It appears as though we need to save it because some new contributor hypothetically could come along in the future and start using it.

In cases such as where nobody currently uses the file.. where the file does not add value to the project.. the file is effectively cruft that should be deleted. Created this ticket since there is disagreement about this concept.

**Comment by PatrickLammers** [comment]
Apparently 'requirement.local.txt' contains the items that a developer needs in order to get the project building...  probably rename it to 'developer.requirements.txt' and leave it in place.  Therefore, I changed the title of this story.
