### ISSUE TITLE
[Task] Define permanent delegation

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#69]
Task | Define permanent delegation
----------|----------
Task Title | Define permanent delegation
User Story | Permanent Delegation #39 
Epic | link associated Epic, if applicable
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | ensure the sum of the story points do not exceed the User Story
Description | A short description
Business Need (the why): | how does this task tie into the user story
Applications or Systems impacted | 
Dependencies | if certain tasks must be done in a certain order, note here
Assumptions | _if any_

**Comment by PatrickLammers** [comment]
This looks like a classic "story to remember to write a story" pitfall...  we will use #39 to describe the functionality of Permanent Delegation
