### ISSUE TITLE
Define Application Global Configuration

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#70]
Epic | Define Application Global Configuration
----------|----------
Epic Title | Global Configuration
T-shirt size default is L(arge) | L
Description | need a way to set application wide variables.  start with simple config for now.  Then build out.
Acceptance Criteria/Tests | There should exist one central place to store application wide variables.  Should be in a human readable format that will allow for embedded comments so that we can describe the use of said variables, the units being used and perhaps some sample settings (alternatively we should build a UI page in the app for seeing these).  Change of global config should NOT require a restart to reread -  See story #541 for hot reloading of settings.

**Comment by PatrickLammers** [comment]
We can let app wide settings live in the .env files for V1, let's revisit this for V2

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
