### ISSUE TITLE
Clean up bin/

### ISSUE THREAD

**Issue by jbobo** [hyperledger/sawtooth-next-directory#705]
Helper files in `bin/` should only contain calls to main methods of the modules they kick off. Clean up helper files and move any superfluous functions/logic into their respective modules. 

Resolves the PyLint E402 ignore.

**Comment by adamgering** [comment]
The only python stuff in bin should be bootstrap files that set TOPDIR and launch main.
ledger_sync, server and tp are correct. Everything else is wrong.

**Comment by adamgering** [comment]
It's not technical debt, except for the test runner (which can similarly be moved and launched via a call to a main function) and db setup, the rest of the wrongness is new ;-)

**Comment by PatrickLammers** [comment]
not a user story either...  it **is** work that needs doing.
