### ISSUE TITLE
[User Story] NEXT Admin - Add

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#71]
[User Story] | NEXT Admin - Add
----------|----------
Epic Title | Define Application Global Configuration #70 
User Story Title | NEXT Admin - Add
T-shirt size: S(mall), M(edium), L(arge) | TBD
Story Points - Fibonacci (1,2,3,5,8,13) | TBD
User Story | [Value Statement] "As a user of a certain type (specify), I want to do something (action) so I can provide business value"
Description | define the admin role, constraint, in line with SOX compliance
Business Need (the why): | from epic, if needed
Details | All the details needed to accomplish the story. Tasks - can be linked
Additional User Story | linked
Acceptance Criteria/Tests | The list of tests or criteria to be used to validate the story has been completed. May still need UAT or SIT / integration testing with other stories.
Failure | if any, fold in negative tests
Definition of Done | e.g.Passes all regression tests, Passes testing per acceptance criteria, Approved by UI team, Able to show feature in demo                                                                                                    
UX/UI Details and/or mockups | if UI change, a mockup or description of what to change, attach image/file
Applications or Systems impacted | upstream/downstream applications/systems
Dependencies | non story dependencies
Assumptions | if any
Performance Considerations | Will the work performed as part of this story impact system performance. If there is potential for a performance hit, where would you expect it to manifest in the system.
Security Considerations | E.g., does this story involve working with Personal Identifying Information (PII)? Note any such security sensitive aspects.
QA Considerations | what might be hard to test or test setup criteria
Acrhitectural/System or Component Impacts | if we're adding something new or significantly changing architecture flag for architect review
Reverse Engineering Required | to document areas not known well by dev team
Questions/Clarifications | Create new issue (add label: question) in this repo and link to this issue

**Comment by PatrickLammers** [comment]
Role admins will be revisited in V2, for now role owners have all the power

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
