### ISSUE TITLE
Add a CONTRIBUTORS.md that sends Hyperledger Access Ticket Emails on Change

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#723]
A recommendation from @ryjones :

Add a CONTRIBUTORS.md file to the project that, when new members are added, sends requests for their repo access to the Hyperledger Help Desk. 

Apparently, this is how they do it in Hyperledger Fabric. I am not sure how, but am assuming in our case that it would involve adding a script to Travis that inspects the file on merge.

Having it in place would save time spend manually sending emails for every new contributor.

**Comment by PatrickLammers** [comment]
not on hyperledger anymore... this is way easier.
