### ISSUE TITLE
Investigate replacing RethinkDb with a Graph database

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#729]
The org structure represented within NEXT is a tree, and a good candidate for persisting trees is the graph database. Investigate the tradeoffs of replacing RethinkDb (a nosql database) with a graph database such as Neo4J: https://neo4j.com/

**Comment by PatrickLammers** [comment]
We should consider doing this if there a clear benefit...  would a graph DB be easier to maintain?  Smaller footprint?  Faster response times?  Let's be clear on which metrics we are going to track this improvement.

**Comment by PatrickLammers** [comment]
closing items that aren't getting traction... revisit if/when ReThink has issues
