### ISSUE TITLE
[User Story] NEXT User - Delete

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#73]
[User Story] | NEXT User - Delete
----------|----------
Epic Title | Define Application Global Configuration #70
User Story Title | NEXT User - Delete
T-shirt size:  | TBD 

User Story | 
Description | can't delete a user who is an owner, what's the constraints or use cases where this is usable
Business Need (the why): | from epic, if needed
Acceptance Criteria/Tests | The list of tests or criteria to be used to validate the story has been completed. May still need UAT or SIT / integration testing with other stories.
Questions/Clarifications | Do we want to be able to do this?  Should we be able to delete a user that we got through syncing to AD or AAD?  Maybe we have another flavor of user that was created in NExt and we should be able to nuke those...  @chrisspanton Even if we have a user that was sync'd from AD and they *do* own packs and roles, if they leave the company they will disappear from AD -- what do we do then?  Do their owned items transition to their manager?

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
