### ISSUE TITLE
[User Story] Non-Blockchain Data Storage

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#74]
User Story | Non-Blockchain Data Storage
----------|----------
Epic | #516
Title | Non-Blockchain Data Storage
T-shirt size default is L(arge) | L
Description | there are instances where we will need to keep this info (org specific)
Business Need (the why): | business value of this feature
Stakeholders | 
Details | All the details needed to accomplish the story. Tasks - can be linked
User Scenarios | names of user stories should suffice
Acceptance Criteria/Tests | _The list of tests or criteria to be used to validate the story has been completed. May still need UAT or SIT / integration testing with other stories._
Failure | _if any, fold in negative tests_
Definition of Done | _e.g.Passes all regression tests, Passes testing per acceptance criteria, Approved by UI team, Able to show feature in demo_                                                                                                    
UX/UI Details and/or mockups | _if UI change, a mockup or description of what to change, attach image/file_
Applications or Systems impacted | _upstream/downstream applications/systems_
Dependencies | 
Assumptions | _if any_
Performance Considerations | _Will the work performed as part of this story impact system performance. If there is potential for a performance hit, where would you expect it to manifest in the system._
Security Considerations | _E.g., does this story involve working with Personal Identifying Information (PII)? Note any such security sensitive aspects._
QA Considerations | _what might be hard to test or test setup criteria_
Acrhitectural/System or Component Impacts | _if we're adding something new or significantly changing architecture flag for architect review_
Reverse Engineering Required | _to document areas not known well by dev team_
Questions/Clarifications | _Create new issue (add label: question) in this repo and link to this issue_

**Comment by adamgering** [comment]
Covered with the metadata table.

The issue is, you may want to store some data imported from identity providers (e.g. office number) and not record the change in that data in a permanent transaction log.

**Comment by PatrickLammers** [comment]
reactivating this one since I'm not convinced it is all taken care of.  We may write some of the data to the metadata table -- but is this everything we want to track?

- Chatbot history
- personal avatar
- previous pw's
- mode to open the UI into when I login
- pack names (not necessarily tied to a user & I don't think ledger gets pack details)

**Comment by PatrickLammers** [comment]
What about global app settings like the expire permissions interval or the lead time to alert on expiring stuff?  I can imagine that an Admin could go to a special UI page and change these values but we need to persist them somwhere so they don't revert on a restart or update of Next.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
