### ISSUE TITLE
[User Story] Migrate to T-Mobile Azure Eventhub instances

### ISSUE THREAD

**Issue by jbobo** [hyperledger/sawtooth-next-directory#755]
User Story | Create new Azure Eventhubs
----------|----------
Task Title | Recover Azure Eventhub instances
Epic | #49 
T-shirt size default is S(mall) | S
Description | rbac-providers-azure was failing to connect to azure. We found that the Eventhub namespace that we use in azure was down and causing the issue. 

The 2 Eventhub instances in the namespace were deleted, so we need to create 2 new Eventhub instances within the old namespace. They were deleted because the account was a demo account with a trial period that expired.

The first Eventhub, an audit log, should take all change logs from our AAD instance and feed them into our StreamAnalytics instance which filters out the events that we can't process. A second outbound log EventHub should be made that takes in logs from StreamAnalytics and makes them available to our rbac-providers-azure service.
Business Need (the why): | Currently blocking in/outbound AAD sync development.
Applications or Systems impacted | rbac-providers-azure

The new EventHubs will be registered with an official, financed TMO account. As such, once setup, they are not expected to disappear again.

**Comment by jbobo** [comment]
Azure dev account was disabled. This task is blocked until we reactivate the subscription or set up another environment and migrate.

**Comment by PatrickLammers** [comment]
This is a NICE TO HAVE for the demo... we will hear from Nick in the dry run on whether or not we should be peeking behind the curtains like this.

**Comment by PatrickLammers** [comment]
It looks like we are still struggling with this one...  we have attention now from the people who can grant permissions so let's get it done in S11 once and for all.
