### ISSUE TITLE
Multi-Party Approval

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#76]
Epic | Multi-Party Approval
----------|----------
Epic Title | Multi-Party Approval
T-shirt size default is L(arge) | L
Description | Allow for system to automatically triage approvals needing more than one person's approval prior to provisioning permissions to applications/systems for a specific person as per request.

Multi-Party Approval
The first supported scenario for multi-party approval will be for re-authorizations.
  

That means, someone is a member of a role, but their membership in that role must be re-confirmed or it will expire.
Re-Authorization is required by at least one role owner, and by the manager of the member.
Thus, from a User Interface standpoint, the first requirement is to visually distinguish Access Requests from Re-Authorization Requests.
We will add a type on the proposal, so you can distinguish them.
For example, presently we have type = ADD_ROLE_MEMBER
We will add REAUTH_ROLE_MEMBER
A question for @ChrisSpanton, if someone REJECTS a REAUTH request, does the member lose access to that role immediately or upon expiration. I presume the former.
The other element of Multi-Party Re-Authorization scenario, is that the user's manager will see the request in addition to the role owners. For this, the User Interface doesn't need to do anything; that assignment happens on the back-end.
So really, that is all there is to our first supported Multi-Party approval scenario. @pgobin
  

To demo this feature, we can configure reauthorization to be required every 6 months, and that re-authorization requests occur 6 months prior to expiration. In reality, the values will be 6 months and perhaps 1 month respectively.

A question regarding this feature, I presume the user should need to enter a reason why they still need access to the role prior to the Re-Auth Request being visible to the approvers? CC @ChrisSpanton 

From a security standpoint, it could be valuable to allow any role owner to require any (or all) existing members to re-authorize. (A manual re-authorization trigger)
We could also configure a SECURITY_LEVEL configuration on a role, and have SECURITY_LEVEL = 1 (default) require 1 role owner, but SECURITY_LEVEL= 2 require 1 role owner + the manager. Thus would be equivalent to the Multi-Party requirements of Re-Auth, but requires no UI change at all.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
