### ISSUE TITLE
[Bug] New proposal not recorded in DB after X proposals have been opened

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#772]
User Story | New proposal not recorded in DB after X proposals have been opened
----------|----------
Description | New proposals stop showing up in Rethink after a few successful records go in
Steps to Repro | Request access to a single role for let's say 5 users. approve access for all 5 roles. only a few then seem to appear in rethink and in the `memberOf` field of the user response object

**Comment by kthblmfld** [comment]
@pgobin please confirm this has been fixed

**Comment by pgobin** [comment]
Closing as fixed.
