### ISSUE TITLE
SX [Bug] API throws 404 user not found after creating new user

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#773]
User Story | API throws 404 user not found after creating new user
----------|----------
Epic Title | (Epic NAME)
User Story Title | API throws 404 user not found after creating new user
T-shirt size: S(mall), M(edium), L(arge) | 
Story Points - Fibonacci (1,2,3,5,8,13) | 1

**Comment by PatrickLammers** [comment]
Per conversation with Phil, this seems fixed now.  
### Not Repro
