### ISSUE TITLE
[User Story] Add bot conversation history to RethinkDB

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#777]
User Story | Add bot conversation history to RethinkDB
----------|----------
User Story Title | Add bot conversation history to RethinkDB
T-shirt size: S(mall), M(edium), L(arge) | M
Story Points - Fibonacci (1,2,3,5,8,13) | 5
User Story | As a user, I want conversation history stored for later retrieval in the UI
Acceptance Criteria/Tests | ?

**Comment by PatrickLammers** [comment]
clearing milestone since Sprint 8 is done.

@pgobin Do you see us keeping ALL chat history for all time?  Or is there a line count max or a time max?  Would "later retrieval in the UI" be as simple as scrolling back up in the chat conversation or are you thinking of a 'search chat history' somehow?

**Comment by pgobin** [comment]
@PatrickLammers My understanding from the UX team is that all history should be stored and scrolling up should go back in time.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
