### ISSUE TITLE
[User Story] Restrict duplicate role and pack names in API

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#778]
User Story | Restrict duplicate role and pack names in API
----------|----------
Epic Title | (Epic NAME)
User Story Title | Restrict duplicate role and pack names in API
T-shirt size: SML | 
Story Points - Fibonacci (1,2,3,5,8,13) | 1
Description | Resource names should be globally unique to avoid collisions in client
Acceptance Criteria | If a user attempts to create a role or pack that would conflict with an existing name, the endpoint should return 200 if name exists, 404 if does not.

**Comment by pgobin** [comment]
Closing as no longer applicable.

**Comment by PatrickLammers** [comment]
reactivating...  I think we a mechanism for restricting duplicate names
