### ISSUE TITLE
Not found screen

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#779]
User Story | 404 screen
----------|----------
User Story Title | 404 screen
T-shirt size: S(mall), M(edium), L(arge) | M
Story Points - Fibonacci (1,2,3,5,8,13) | 5
User Story | As a user I want to land on a 404 screen given I visit an unsupported route.
Description | A short description 
Business Need (the why): | from epic, if needed
Details | On visiting an unsupported route show a 404 screen. In the event a role or pack doesn't exist, display a 404 screen.
Additional User Story | linked
Acceptance Criteria/Tests | The list of tests or criteria to be used to validate the story has been completed. May still need UAT or SIT / integration testing with other stories.
Failure | if any, fold in negative tests
Definition of Done | 404 screen surfaces in reasonable scenarios.

**Comment by PatrickLammers** [comment]
This needs a real user story.  Why would our app ever hit a 404?  I can envision having no content to show and leaving the user with an empty screen but when would a 404 page ever come up?
