### ISSUE TITLE
[User Story] [Next UI] Multi-Party Approval

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#78]
[User Story] | [UI Implementation] Multi-Party Approval
----------|----------
Epic Title | Multi-party approval #76 
User Story Title | UI Implementation - Multi-Party Approval
T-shirt size: S(mall), M(edium), L(arge) | L
User Story | "As an individual contributor, my role access with expire on a regular basis.Renewal requests will be automatically generated and NEXT will require approval from the role owner and my manager before acting on the request.  This ensures that only people with a business need will have access to the roles.
Acceptance Criteria/Tests | Once a renewal request is triggered and is in process, a user should be able to see the approval status in the UI for both approvers.

**Comment by PatrickLammers** [comment]
Let's use this story to track the suggestions for the demo UI.  I will tweak the description above to reflect our recent discussions

**Comment by pgobin** [comment]
Closing as multi-party has been decomposed into several smaller user stories.
