### ISSUE TITLE
[User Story] Approved screen - Ability to sort table

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#781]
User Story | Approved screen - Ability to sort table
----------|----------
T-shirt size:  | 
User Story | "As an Approver in NexT, I need to be able to sort through my history of approvals and find the one I am looking for...  I should be able to sort this table by any of the available columns."
Acceptance Criteria/Tests | show how easy it is to sort the table in various ways by resorting on the columns.  Is it safe to assume that I can sort by the column by clicking the title and clicking it again reverses the sort.  Demo should include viewing a very long table (if we paginate and then reverse the sort do we just resort the current page or quickly swap to the last page?).

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
