### ISSUE TITLE
[Bug] Individual Requests - Selection checkbox indeterminate state incomplete

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#782]
Bug | Individual Requests - Selection checkbox indeterminate state incomplete
----------|----------

Repro:

1. Go to individual requests
2. Make sure there are multiple pending
3. Make selections and switch between views
4. Notice sometimes box is unchecked or fully checked when it should be partially checked (dot)

**Comment by PatrickLammers** [comment]
How does this bug manifest itself to the user?  What are the repro steps?
