### ISSUE TITLE
[User Story] Add creation timestamp to proposal

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#786]
User Story | Add creation timestamp to proposal
----------|----------
User Story Title |  Add creation timestamp to proposal

**Comment by PatrickLammers** [comment]
is this so we know when access to a role will expire?  Or is this on an access request and would be used to escalate when it has sat for too long?  We need a real user story around this...

**Comment by PatrickLammers** [comment]
Ahh...  This is the timestamp used here?
![image](https://user-images.githubusercontent.com/45403188/50565398-48343000-0ce3-11e9-896a-b184958b35a2.png)

**Comment by adamgering** [comment]
Added to data model in PR #857 as created_date and closed_date
