### ISSUE TITLE
[User Story] API should support batch proposal creation in single request

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#788]
User Story | API should support batch proposal creation in single request
----------|----------
Epic Title | (Epic NAME)
T-shirt size: | 
User Story | "As a developer of the UI for NEXT (?), I would prefer to be able to make a single call that passes a list of proposals to create instead of needing to loop through the list and create the individually.  This is more efficient (true?)"
Description | A short description 
Details | All the details needed to accomplish the story. Tasks - can be linked
Acceptance Criteria/Tests | The list of tests or criteria to be used to validate the story has been completed. May still need UAT or SIT / integration testing with other stories.

**Comment by PatrickLammers** [comment]
@pgobin @kthblmfld  I've updated the user story above -- please review and make sure it still makes sense.  Story #37 talks about batch approval looping through items at the UI level.  This is batch creation though...  would we take the same approach here?

**Comment by PatrickLammers** [comment]
PR #1069 is supposed to address this issue...
