### ISSUE TITLE
[User Story] Email template - Org chart

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#789]
User Story | Email template - Org chart
----------|----------
Epic Title | (Epic NAME)
User Story Title | Email template - Org chart
T-shirt size: S(mall), M(edium), L(arge) | 
Story Points - Fibonacci (1,2,3,5,8,13) | ?
User Story | As a user, I want to view the org chart in approval email template
Business Need (the why): | Email improves productivity
Acceptance Criteria/Tests | ?

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
