### ISSUE TITLE
S3 [User Story] [UI Design] Design Components Definitions

### ISSUE THREAD

**Issue by chimpuz** [hyperledger/sawtooth-next-directory#79]
[User Story] [Epic] | [UI Design] Design Components
----------|----------
Epic Title | NA
User Story Title | ([UI Design] Design Components
T-shirt size: S(mall), M(edium), L(arge) | L
Story Points - Fibonacci (1,2,3,5,8,13) |  S2 - 2 story points S3 - 3 story points
User Story | The user story involves defining/designing the components needed for the defining workflows for each user-story. 
Description | The following items are covered as a part of this: Chat conversation variations, Chat action types, System generated channels, Bot design and tonality, Indicator icon family, Tracking types, Roles/Groups Body, Auto approval configuration/indication
Business Need (the why): | 
Details | All the details needed to accomplish the story. Tasks - can be linked
Additional User Story |
Acceptance Criteria/Tests | 
Failure | 
Definition of Done |                                                                                                 
UX/UI Details and/or mockups | UX/UI Details
Applications or Systems impacted | upstream/downstream applications/systems
Dependencies | 
Assumptions | 
Performance Considerations | 
Security Considerations | 
QA Considerations | 
Acrhitectural/System or Component Impacts | 
Reverse Engineering Required | 
Questions/Clarifications |

**Comment by agoldingay** [comment]
Added to Sprint 2 (milestone) during 9/17/18 Sprint planning meeting.

**Comment by codingalyona** [comment]
S2 = 2 STORY POINTS DONE. S3 - 3 points left. need another session this week.- we'll schedule.

**Comment by chimpuz** [comment]
We will defer the next session for Chatbot iteration once we are working on the related User Stories.  Will sync up the with current variations in next couple of days.
