### ISSUE TITLE
Email - Webhook for 'Approve/Reject' flow from email

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#790]
User Story | Email - Webhook for 'Approve/Reject' flow from email
----------|----------
Epic Title | Alerting
T-shirt size:  | 
User Story | "As an Approver in NEXT, I want to be able to respond approval requests directly in the email message I receive to approve or reject a request without opening the NEXT client.  This allows me to respond to approvals in a timely manner."

**Description** 
- Any email notification requiring action on the recipient's part should include the appropriate response buttons.
- pressing the buttons in the mail registers the response with NexT application the same as it would if the response had been made via the UI
- The types of emails that will use this feature include (but not limited to)
     - Singleton approval requests
     - delegation requests

Question: 
- what do we do for summarized access request emails?  When reauth season kicks off, I would rather get one mail with 15 requests than get 15 emails with one request each.  Will the email have the capability of selecting a subset of the requests and approving?  Maybe the right thing for such emails is to have APPROVE ALL, REJECT ALL buttons and direct the recipient to the client UI if they wish to make subset selections.
- Are the buttons disabled somehow once I have responded the first time?  Should a response somehow move the mail to the deleted items folder (like meeting requests in Outlook?)

**Acceptance Criteria/Tests**
- For the given email requests above, user shall be able to respond by selecting the buttons in the UI.
- reopening the mail and responding in a different way is the same as story #1229 -- it records a second response that supersedes the first one.
- demonstrate that this functionality works with top 5 most popular corporate email clients (as well as on devices)

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
