### ISSUE TITLE
[BLOCKED] [User Story] Expire screen

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#792]
User Story | Expire screen
----------|----------
User Story Title | Expire screen 
T-shirt size: S(mall), M(edium), L(arge) | M
Story Points - Fibonacci (1,2,3,5,8,13) | 2
User Story | As a user, I want to a screen that displays my soon-to-expire and expired roles.
Description | Create expire screen
Business Need (the why): | View improves productivity
Acceptance Criteria/Tests | Expire screen reasonable matches mocks
UX/UI Details and/or mockups | if UI change, a mockup or description of what to change, attach image/file
Applications or Systems impacted | upstream/downstream applications/systems
Dependencies | Role expiration timestamps must exist

**Comment by PatrickLammers** [comment]
Does this depend on #861?  That story deals with my permissions for a given role expiring.  Or is this more about a request that hasn't been approved timing out (expiring)?  I can't tell without a screen shot.

**Comment by PatrickLammers** [comment]
Moving to S11 based on chat with Phil.  While this story was written about soon-to-expire stories, he has ideas on how it can also display your recently expired roles.
@pgobin  Should old, expired roles fall off this list ?

**Comment by pgobin** [comment]
@PatrickLammers We'll need to get some input on that.

**Comment by PatrickLammers** [comment]
Adjusting the estimate to 2 based on discussion with Phil.  This is the estimate to get the page up in the UI with 'Expired' content... we might need to revisit how we deal with 'soon to expire' once we see this...

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
