### ISSUE TITLE
S8 [User Story] Email - HTML Template

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#793]
User Story | HTML Template
----------|----------
Epic Title | (Epic NAME)
User Story Title | HTML Template
T-shirt size: S(mall), M(edium), L(arge) | 
Story Points - Fibonacci (1,2,3,5,8,13) | 2
User Story | As a user, I want an email template for the owner to take action on a proposal.
Description | A short description 
Business Need (the why): | Actionable emails improve productivity
Details | All the details needed to accomplish the story. Tasks - can be linked
Additional User Story | linked
Acceptance Criteria/Tests | Not sure yet

**Comment by Akashkotian7** [comment]
I have started working on this.
