### ISSUE TITLE
S8 [User Story] Document and bring back staging env

### ISSUE THREAD

**Issue by mtn217** [hyperledger/sawtooth-next-directory#796]
[User Story] | Document and bring back staging env
----------|----------
T-shirt size: S(mall), M(edium), L(arge) |  S 
Story Points - Fibonacci (1,2,3,5,8,13) |  2
User Story | [Value Statement] "As a user attempting to demo the NEXT platform, I want to have a staging environment that has the most updated code from Hyperledger's master branch so I can show off the latest changes that have been developed."
Description | Document the steps needed to manually update the two staging environments (AWS + Azure) and manually pull Hyperledger's master branch. 
Business Need (the why): | The staging platforms will be used for demoing our product. 
Acceptance Criteria/Tests | 1) Have documentation that allows the team to be able to manually update the staging environments themselves. 2) Manually update the staging environment to the latest master repo (preferably perform one right before demo).

**Comment by jbobo** [comment]
Attempted to migrate to an internal enterprise dev AAD instance/subscription. The initial plan was to create a new EventHub in another subscription and point it at our old AAD instance (which is still running without a subscription). However, exporting audit logs is a feature that requires a subscription to activate. We'll need to completely migrate to the internal AAD instance/subscription. Unfortunately exporting audit logs requires admin privileges (which have been requested). Expecting this ticket to be resolved by EOD Monday.

**Comment by jbobo** [comment]
Fortunately, Microsoft has already documented the steps to streaming Azure AD audit logs to an EventHub instance (https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/tutorial-azure-monitor-stream-logs-to-event-hub)
