### ISSUE TITLE
Implement Custom Image Support

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#804]
In the NEXT UI are user image stubs. In order to make these actual images that users can manage, there needs to be a service and repository (ie lightweight CMS) on the backend that allows the UI to implement this feature.
- Create the service for user image management
  - Create an endpoint for multipart file upload POSTs by userId
  - Create an endpoint for retrieving the latest user image using a GET
  - Determine the most effective means of storing/retrieving the user images (file system, database, and trade-offs)

- Feature: Users can upload their own profile images
- Feature: Pack editors can upload an image/avatar for their specific Pack

**Comment by PatrickLammers** [comment]
This is to support users uploading their own avatars and custom images for advertising roles and packs, right?  So I would expect some UI on role/pack creation and maybe some on my profile/settings.

Does AD/AAD support user images now?  I know a lot of places attach your headshot for use in things like Outlook or WorkDay.  If we allow users to upload their own,are we syncing back to AD?

What stops people from uploading images of their pets, kids or meme's from the internet?

**Comment by PatrickLammers** [comment]
will revisit this if we decide to support avatars for roles & packs & people in the future
