### ISSUE TITLE
Implement server-side pagination for api calls yielding high results

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#806]
In cases where a view in NEXT comprises data that can potentially become very large (eg browsing proposals, users, roles, packs. https://www.dropbox.com/s/ccdzd1dy7bfo3xc/B1.png) implement server-side pagination to cut down the payload/time over the wire. 

- [ ] Determine where the data is being queried from (formerly pseudo-relational tables, more recently 'state')
- [ ] Add support to the endpoint for limiting the range of results ( query params )
- [ ] Write the query that filters on the given range params

Acceptance criteria: 
- Demo in the UI. If the feature is not available in the UI, demo using a rest client.
- Given a GET request to a lookup endpoint having a specified page length, the api should yield a list of results that is less than or equal to the specified page length. If results = 12, page size is 10, then page 1 should have 10 results.
- The api should be able to show traversal across several pages. If results = 50, page size is 8, then the call for page 2 should return (considering base index of 1) results in 9-16.
- Traversals should stop at either end of the list without breaking. If results = 15, page size is 10, then page 2 should have 5 results and traverse no further.
- Paging should be stateless. Any lookup of any range of results should be available in the api at all times. Any and all state management must happen in the UI.

**Comment by PatrickLammers** [comment]
I took the liberty of rewriting #847 and now it seems to overlap this story quite a bit.  The desired end user experience would be that everything in the UI seems very fast and responsive...  Not sure if this can be accomplished without some sort of client side caching though.  Please take a look at #847 and decide if this story is in direct conflict or is complimentary.

In general we should try to write stories that describe the desired functionality and not the implementation...  I like most of the Acceptance Criteria on this one.

**Comment by PatrickLammers** [comment]
took off UI Design tag since this story is describing server side pagination...  at most it makes the UI speed up.  No need for design changes as far as I can tell.

**Comment by PatrickLammers** [comment]
per discussion with Phil, we have pagination for much of the app already.  We will revisit this if we have perf issues.
