### ISSUE TITLE
Track average approval time

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#807]
Track the average approval time (turnaround time of requests to approvals) in RethinkDb. 

TODO: Narrow the scope of avg. approval time by associating it to something else (proposal_type, approver, etc)

Once this is complete: #808 can proceed.

**Comment by PatrickLammers** [comment]
@kthblmfld to address the TODO above.  I would guess that the correct calculation would be "average time to approve requests to this role"  Since a role may have multiple owners we can't really tie it to one approver.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
