### ISSUE TITLE
Add average approval time to the api

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#808]
As a user of the NEXT client, it would be very interesting to see the average approval time for the role I am requesting.  This will let me know how long I should expect to wait and maybe when I should start escalating if I haven't received approval.

See the footer in this wireframe: https://www.dropbox.com/s/s5agqkvxegxmgqd/U3.png

Expose this value via a new endpoint in the NEXT rest api. 

NOTE: This story depends on the completion of #807

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
