### ISSUE TITLE
[User Story]  Document DB schema 

### ISSUE THREAD

**Issue by PatrickLammers** [hyperledger/sawtooth-next-directory#815]
User Story | "As a developer on NEXT, I need to know the structure of the tables within our db so that I can do my work & provide business value"

Description | While we value face to face communication, sometimes it's key to write documentation  This is one of those times.

**Comment by kthblmfld** [comment]
@PatrickLammers to add some clarification: We need to document object relationships in the system ( ie the domain model ).

@adamgering Please include Dustin in these discussions.

**Comment by adamgering** [comment]
PR #818 was merged this morning.

**Comment by PatrickLammers** [comment]
Not sure how #818 relates to this issue...  Nadia tells me that since the older versions of the data tables are going to remain for the time being, we can build our demo functionality using them.  Therefore, this is no longer blocking (and not critical for S8)

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
