### ISSUE TITLE
[User Story] Unique Version stamp on each build,

### ISSUE THREAD

**Issue by PatrickLammers** [hyperledger/sawtooth-next-directory#822]
User Story  | Visible version stamp in NEXT UI.
---------|----------
T-shirt size:  | S
User Story | We should have a way to uniquely identify each build of our application.  This lets us communicate to our users in a definitive manner regarding functionality and bugs.

**Description**  : This can be implemented a number of ways...  an About box in the UI somewhere is one example.  Each automated build should be tagged with a unique number that follows a predictable pattern.  ~~"Major.minor.date.time" is one such pattern but if our build system automatically generates one too then we could use that.~~ As per Dustin's suggestion we'll use the short hash of the most recent git commit (you can get this running `git describe --tags` in the repo). Useful information on setting up git tagging (which we haven't done yet) can be found [here](https://stackoverflow.com/questions/5694389/get-the-short-git-version-hash), [here](https://git-scm.com/book/en/v2/Git-Basics-Tagging), and [here](https://coderwall.com/p/hwmmsq/sync-application-version-with-git-tag-automatically).

**Acceptance Criteria** 
1) Each merge to master should trigger a new version stamp, 
2) Version is visible to user in the UI, 
3) build log should include version info so we can recreate the state of the product to any point in the past.

Tasks:

- [x] Save version number from the VERSION file in .env file. Pass the verison number to the front end client service.

- [ ] Display version number on UI

**Comment by PatrickLammers** [comment]
we seem to have missed one of the acceptance criteria on this story.  I still don't see a version number in the UI anywhere

**Comment by jbobo** [comment]
before we add that version flag to the UI I'd suggest we talk to the front end team and assess how much work it will take. Once we implement a branching scheme with stable releases we'll be able to use the release tag (or whatever we use to track releases) instead of the `VERSION` file (which has been causing some friction in the PR process).

**Comment by PatrickLammers** [comment]
Revisiting the versioning scheme as part of the branching approach.  move to later sprints once we have a branching plan.

**Comment by jbobo** [comment]
This will be completed as a part of implementing git-flow as our branching scheme. We agreed to keep using a semantic version number as well as the VERSION file (in lieu of git-tags), but only increment the version file on the official release as part of the PR from `develop` to `master`.
