### ISSUE TITLE
Add attributes to Proposals to be displayed in the UI

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#823]
Api: getProposals()

For each proposal, include:
  - User-friendly hash
  - Date-created timestamp
  - Role identifier

**Comment by PatrickLammers** [comment]
Help me visualize where these go in the UI...
Can we link this to the UI story where we are trying to show these details?  
Or attach a screenshot from the UI team with these items displayed? 

Thanks

**Comment by PatrickLammers** [comment]
phil says he has what he needs
