### ISSUE TITLE
[UI Design] Expiration of Access

### ISSUE THREAD

**Issue by chimpuz** [hyperledger/sawtooth-next-directory#83]
Task | Define Expiration of Access use cases
----------|----------
Task Title | [UI Design] Expiration of Access
User Story | link associated User Story for this task
Epic | link associated Epic, if applicable
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 3
Description | Define workflow & mock-ups for Expiration of Access use cases
Business Need (the why): | 
Applications or Systems impacted | 
Dependencies | 
Assumptions | _if any_

**Comment by PatrickLammers** [comment]
Expire doesn't need any further work.  Closing
