### ISSUE TITLE
Upgrade to Sawtooth 1.1.4 and test and fix everything that breaks

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#838]
User Story | Upgrade to Sawtooth 1.1.4 and test
----------|----------
T-shirt size: | 
User Story | "As a NexT dev, I want the latest and greatest software in my project"

**Description**
We should strive to stay current with the Sawtooth community and make incremental changes as things evolve.  Testing is insufficient -- we need to test and FIX anything that results from this update.

**Acceptance Criteria/Tests**
- all functionality of Next should still work as it did before (if not _better_)

**Comment by PatrickLammers** [comment]
@adamgering Upgrading Sawtooth would only affect our Blockchain functionality, yes?  We should add to the acceptance criteria section of this story to detail what sort of testing we will be doing?  

Is there specific new functionality that Sawtooth 1.1 enables that we would want to adopt?  If so, let's discuss so we can get stories added and linked here as dependents.

**Comment by Nonj** [comment]
sawtooth-sdk version 1.1.4 currently does not contain the protobufs package within it. (No clue why because in the 1.1.4 documentation it says it does).

Since we use the package in several different modules, test modules, etc. I think this should be in the backlog before I proceed any further.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
