### ISSUE TITLE
[UI Design] Re-authorization of Access

### ISSUE THREAD

**Issue by chimpuz** [hyperledger/sawtooth-next-directory#84]
Task | Define Re-authorization of Access use cases
----------|----------
Task Title | [UI Design] Re-authorization of Access
User Story | link associated User Story for this task
Epic | link associated Epic, if applicable
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 3
Description | Define workflow & mock-ups for Re-authorization of Access use cases
Business Need (the why): | 
Applications or Systems impacted | 
Dependencies | 
Assumptions | _if any_

**Comment by PatrickLammers** [comment]
re-auth UI doesn't need any further work...  closing
