### ISSUE TITLE
[UI Design] Creation of virtual Roles (aka "Packs")

### ISSUE THREAD

**Issue by chimpuz** [hyperledger/sawtooth-next-directory#85]
Task | [UI Design] Creation of virtual Roles
----------|----------
Task Title | [UI Design] Creation of virtual Roles
User Story | link associated User Story for this task
Epic | #529 
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 3
Description | Define workflow & mock-ups for Creation of virtual Roles use cases
Business Need (the why): | 
Applications or Systems impacted | 
Dependencies | 
Assumptions | _if any_

**Comment by PatrickLammers** [comment]
the UI design of packs seems to be done.
