### ISSUE TITLE
Validate/verify 'on_behalf_of' business logic

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#853]
When an approval comes in with 'on_behalf_of' set (see #852):
  - Fetch the user associated with the userId specified by 'on_behalf_of'
  - Verify the user is below the approver in the org chart/hierarchy/reporting chain
     - Reject approvals not meeting these criteria
     - Confirm approvals meeting these criteria

**Comment by PatrickLammers** [comment]
@kthblmfld This story sounds like we are trying to verify the org chart for on_behalf_of requests in case they should be disallowed...  but wouldn't the app prevent me from creating such a request unless I had that approval?  Are we doing the check here as an additional security step in case someone manages to inject a request without permissions?

**Comment by PatrickLammers** [comment]
replaced with #1217
