### ISSUE TITLE
Implement approval request escalation trigger

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#854]
Add the capability to escalate an approval request to NEXT. This feature will assist in demoing functionality, and may serve a practical purpose to the UI:
  - Create an endpoint that, when called via POST, escalates an approval request up a level in the org hierarchy.
    - Lookup the approval request
    - If found and still open, find the designated approver
    - Lookup the person (boss) in the org hierarchy the designated approver reports to
    - Assign the approval request to the boss.

**Comment by PatrickLammers** [comment]
Escalation of approval requests is a V2 feature

**Comment by PatrickLammers** [comment]
This seems to be just a test or a demo feature... not for general release.  Closing
