### ISSUE TITLE
Setup SSL/TLS connections on NEXT Demo environment

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#855]
User Story Title | Setup SSL/TLS connections on Demo environment
----------|----------
User Story | Setup SSL/TLS connections on Demo environment
T-Shirt Size | S
Story Points | 2
User Story | "As a Sawtooth NEXT consuming enterprise, I want my personally identifiable information to be protected in transit"
Description | Setting up SSL/TLS connections (use https versus http) on our demo environment will ensure data is being encrypted as it goes through the NEXT demo. One method we could go with is to implement an optional NGINX container, pass in an SSL certificate that listens on port 443 and redirects traffic to port 4201.
Business Need (the why): | SSL/TLS connections are needed to encrypt traffic within NEXT and prevent malicious actors from sniffing the traffic, helping us satisfy privacy laws.
Acceptance Criteria/Tests | The UI and REST API endpoints should be available at https://next.corporate.t-mobile.com
Applications or Systems impacted |
Details | Explore the HL projects for self-signed certs in pre-prod environments, https://hyperledger.github.io/composer/v0.19/integrating/securing-the-rest-server

**Comment by nadiabahrami** [comment]
We don't think we need this for the demo - taking DEMO tag off

**Comment by PatrickLammers** [comment]
This is titled as a Task but it doesn't seem to be in support of any other story.  Also sounds like it may be a non-trivial bit of work.  Should it be a story instead?

**Comment by PatrickLammers** [comment]
Will we need SSL to go to PROD PARALLEL?

**Comment by PatrickLammers** [comment]
NGINX is an implementation detail -- leaving it in the above but it probably shouldn't be considered as requirement.  The goal of the story is to use secure connections within Next.

**Comment by PatrickLammers** [comment]
chatbot apparently has issues... bumping the estimate and moving out of s12

**Comment by PatrickLammers** [comment]
needs to work for the following:

next.corporate.t-mobile.com
stage.next.corporate.t-mobile.com
dev.next.corporate.t-mobile.com
