### ISSUE TITLE
Create address for user_proposal

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#858]
Add to the rbac addresser: user_proposal

**Comment by PatrickLammers** [comment]
From kthblmfld via RocketChat @ 11:31 AM

Every proposal type (action performed, event to be recorded) requires an encoding in the addresser. The Addresser is what determines the final resting place of the actual data in the blockchain. There are likely a number of stories along these lines as a result of some elaboration I was doing with Adam. Not sure where the project stands with regards to what is complete, but you can find out by looking at the usages of address_space.py

Looks like this has changed a bit from the time the story was written, but that there are implementations for createUser and importUser

**Comment by PatrickLammers** [comment]
No one currently on the project knows what this was about... closing per conversation with George
