### ISSUE TITLE
[User Story] - Add expiration date to roles so that a user's credentials can expire

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#861]
[User Story] | Add expiration date to roles so that a user's credentials can expire
----------|----------
Epic Title | Multi - approval
User Story Title | [User Story] - Add expiration date to roles so that a user's credentials can expire
T-shirt size: S(mall), M(edium), L(arge) | s
User Story | We need to add an expiration date for the user's access to a role to be able to expire them
Description | Add expiration date to roles so that a user's credentials can expire them so that they can be shifted to a need for reauthorization.  This is for Demo as we need to see the demo of the expiration feature

**Comment by kthblmfld** [comment]
There is no specification of where or how expiration date should be added to Role.

Shall it be configurable upon creation (ie this new role has an enrollment period of x days)?
Expiration date is not in the spec for Role. Adding it to metadata
