### ISSUE TITLE
Re-Authorization: Create new messages for reauthorizations

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#862]
Create new messages for re-authorizations.

A "re-auth" request for role membership will need permission from both the role owner and the requestor's organizational manager.  This type of request shouldn't be acted upon until both permissions have been given.

If either approver rejects the proposal, the user's access to the role shall remain until it expires normally.  (the rejection is on the approval to reauth, not on their current access)

If both approver's Approve of the proposal, the new approval date in the user's access will be set to current date.  

Question: given that last line above, we will lose some history regarding how long a user has had this access -- we won't know he has been reauthed several times  -- do we care?  It should be written in the ledger anyway and can be reviewed there.

**Comment by kthblmfld** [comment]
@adamgering Please fill in the details for this story

**Comment by PatrickLammers** [comment]
@kthblmfld needs an estimate.

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
