### ISSUE TITLE
Implement "Add owner to role"

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#863]
User story: As a NEXT manager/role owner, I want to add additional owners to a role

User requests role ownership
Proposal is created
On approval, user is assigned to role owners

Workaround: Create this in Ldap and apply via import

**Comment by PatrickLammers** [comment]
Question:  Seems like maybe there should be two ways to initiate the 'add an owner' scenario.  
1) current owner desires a co-owner so she adds someone via role details UI and that user must accept (like a delegate does)  
2) a regular user asks to be promoted to owner so he requests to be made an owner.  Current owner must approve.

In either case, once approval is received, they get added to the list of role owners.  

We should be clear on the distinction between the two -- and get clarification from PO on which one to implement first.

Is multiple owners a Release 1 criteria for T-Mo scenarios?

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
