### ISSUE TITLE
[Bug] Role that user is already a part of does not appear under 'My Roles

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#880]
Bug - Role that user is already a part of does not appear under 'My Roles'
----------|----------
Task Title |
User Story | link associated User Story for this task
Description | when a user is already a part of a group and not requesting it via a proposal I am unable to see it in the side bar under my roles.   
Repro steps:
1. Run authorization script
2. Login as CaptainAmerica@TmoBlockchain.onmicrosoft.com
You should now be seeing the image added to this, where he is part of the Avenger's group, but it is not listed as such in the sidebar.  ![Screen Shot 2018-12-20 at 3.43.48 PM.png](https://images.zenhubusercontent.com/575921babf93871ccd9c5898/745b347a-a8c1-4ff9-ac9e-802e5ceb7b12)

**Comment by pgobin** [comment]
Addressed in PR #956.
