### ISSUE TITLE
[BUG] browse roles doesn't show the correct number of member in the role

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#884]
Task | browse groups doesn't show the correct amount of groups
----------|----------
Description | When viewing groups from the browse section we are unable to get the real amount of members in them.  Example is avengers
Repro steps:
1) Login
2) Click browse
3) Look at Avengers group 0 members
4) click on avengers
5) Two members in it
(Images attached)
![Screen Shot 2018-12-21 at 12.28.28 AM.png](https://images.zenhubusercontent.com/575921babf93871ccd9c5898/869ddca6-7e3f-472a-9848-47f5e5fee731)
![Screen Shot 2018-12-21 at 12.28.37 AM.png](https://images.zenhubusercontent.com/575921babf93871ccd9c5898/781f4211-3452-4cdc-b326-11f4ffaa1599)

**Comment by pgobin** [comment]
Fixed in #897.
