### ISSUE TITLE
Persistent avatars in the UI

### ISSUE THREAD

**Issue by PatrickLammers** [hyperledger/sawtooth-next-directory#893]
User Story | Persistent Avatars 
----------|----------
T-shirt size: S(mall), M(edium), L(arge) | 
User Story |  "As any user of NEXT, I have an avatar that is used throughout the UI of the app to identify me. "
Description | Ideally we support image upload and have the ability to pull existing images from AD (if there) For the demo, we should at least have a single image that follows a person around.  Perhaps just using a default bust outline or user initials would suffice for the demo. 
Acceptance Criteria/Tests | Upon creation of new user, I am assigned an avatar icon that follows me throughout the UI.  The same icon/avatar should be consistent across sessions.

**Comment by pgobin** [comment]
All avatars except login screen avatar are updated. Closing as login screen requires separate considerations, and the criteria are otherwise met.
