### ISSUE TITLE
Get the friendly URL working again for demo

### ISSUE THREAD

**Issue by PatrickLammers** [hyperledger/sawtooth-next-directory#895]
User Story | We shouldn't have to remember an arcane IP address, get the friendly URL again
----------|----------
T-shirt size: S(mall), M(edium), L(arge) | 
User Story | [Value Statement] "As a user of a NEXT, I should have an easy to remember URL.  We had http://next.corporate.t-mobile.com:4201 working previously, let's get it back."
Description | A short description 
Acceptance Criteria/Tests | This URL works as the equivalent to the IP address.

**Comment by jbobo** [comment]
http://tm/nextstg

**Comment by PatrickLammers** [comment]
Chris would like to see our demo running with SSL and the corporate domain before showing the demo.  Let's take another crack at this one.

**Comment by mtn217** [comment]
@PatrickLammers - This ticket will be dedicated to getting the friendly URL (next.corporate.t-mobile.com:4201) back. Tickets #855 and #149 will be used to add SSL to our demo environment.

next.corporate.t-mobile.com:4201 is now currently pointing to our demo environment and will be used for our demo from now on.
