### ISSUE TITLE
BUG -- initial landing page chatbot UI not in sync

### ISSUE THREAD

**Issue by PatrickLammers** [hyperledger/sawtooth-next-directory#896]
Currently when I log into NEXT, I am dropped into a role page and chatbot is suggesting that perhaps I would benefit from getting permissions for a role.  The role on the page and the role suggested by Chatbot are not the same...  

Also, when I ask for this role, Chatbot demands that I draft a message for "none" -- I'm assuming this should be the owner of the role.  Are we grabbing a real field from the backend that isn't populated yet -- or is this UI hardcoded this way?

**Comment by pgobin** [comment]
Addressed in #1011.
