### ISSUE TITLE
[User Story] UUID mapper

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#899]
[User Story] | UUID mapper
----------|----------
Epic Title | #333 
User Story Title | UUID mapper
T-shirt size: S(mall), M(edium), L(arge) | M
User Story | A user that exists in AD should also be able to exist in AAD without creating a duplicate user record, to support companies who may migrate from AD to AAD or otherwise utilize multiple identity providers and identity provider migrations.
Description | Maps multiple UUIDs from providers or other sources to the UUID used by NEXT.
Acceptance Criteria/Tests |

**Comment by PatrickLammers** [comment]
a relic of a design meeting that we are rejecting now.
