### ISSUE TITLE
[Epic] Infrastructure Build

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#90]
Epic | Infrastructure Build
----------|----------
Epic Title | e.g. Active Directory Integration
T-shirt size default is L(arge) | L
Description | A short description
Business Need (the why): | business value of this feature
Stakeholders | 
Details | All the details needed to accomplish the story. Tasks - can be linked
User Scenarios | Dev environment, Master environment
Acceptance Criteria/Tests | _The list of tests or criteria to be used to validate the story has been completed. May still need UAT or SIT / integration testing with other stories._
Failure | _if any, fold in negative tests_
Definition of Done | _e.g.Passes all regression tests, Passes testing per acceptance criteria, Approved by UI team, Able to show feature in demo_                                                                                                    
UX/UI Details and/or mockups | _if UI change, a mockup or description of what to change, attach image/file_
Applications or Systems impacted | _upstream/downstream applications/systems_
Dependencies | 
Assumptions | _if any_
Performance Considerations | _Will the work performed as part of this story impact system performance. If there is potential for a performance hit, where would you expect it to manifest in the system._
Security Considerations | _E.g., does this story involve working with Personal Identifying Information (PII)? Note any such security sensitive aspects._
QA Considerations | _what might be hard to test or test setup criteria_
Acrhitectural/System or Component Impacts | _if we're adding something new or significantly changing architecture flag for architect review_
Reverse Engineering Required | _to document areas not known well by dev team_
Questions/Clarifications | _Create new issue (add label: question) in this repo and link to this issue_

**Comment by agoldingay** [comment]
Epic created based on conversations to address setting up environments during 9/14/18 stand-up. To be further groomed.

**Comment by PatrickLammers** [comment]
This story has zero usable content.  Closing
