### ISSUE TITLE
[Bug] Can't tell what symbols mean

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#921]
Description: Can't tell what symbols on the users mean.  The shield and the key does not tell me that they are admins and owners respectively.  

![Screen Shot 2018-12-27 at 9.41.27 AM.png](https://images.zenhubusercontent.com/575921babf93871ccd9c5898/bad92d48-8fb2-4503-9c58-7faa83788fe3)
![Screen Shot 2018-12-27 at 9.33.07 AM.png](https://images.zenhubusercontent.com/575921babf93871ccd9c5898/8469ac23-f128-4467-b15c-c67c589fd666)

**Comment by PatrickLammers** [comment]
Perhaps a tooltip on hover?
