### ISSUE TITLE
[Bug] Organization page manager's name is cut off due to overlap issue

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#923]
Task | Organization page direct manager's name is cut off due to overlap issue
----------|----------
Description | When navigating to the org page on first load the direct manager's name is cut off due to a spacing issue.

![Screen Shot 2018-12-27 at 2.15.51 PM.png](https://images.zenhubusercontent.com/575921babf93871ccd9c5898/e82db72b-8134-4fc9-8c92-62b4483e8091)

**Comment by pgobin** [comment]
Solved in #968 by removing scroll.
