### ISSUE TITLE
[Bug] Chatbot does not render switching between approver and non-approver

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#926]
Task | Chatbot does not render switching between approver and non-approver
----------|----------
Description | The chatbot when rendered on the non-approval side is interactable to ask for roles.  But when switching over the chatbot does not appear, but you can still interact with it.  So when you go back the conversation is there, but you can't see your interaction

The 'hi' and 'hola' in the images below were typed when screen was blank.  

![Screen Shot 2018-12-27 at 4.19.59 PM.png](https://images.zenhubusercontent.com/575921babf93871ccd9c5898/f06a365e-3656-4926-8f95-290fc510b786)
![Screen Shot 2018-12-27 at 4.20.05 PM.png](https://images.zenhubusercontent.com/575921babf93871ccd9c5898/9530a688-4285-476b-8729-1c5ad51e3a55)
![Screen Shot 2018-12-27 at 4.20.13 PM.png](https://images.zenhubusercontent.com/575921babf93871ccd9c5898/27f2678d-1680-452e-b9ce-307fba086eec)

**Comment by pgobin** [comment]
Closing as fixed.
