### ISSUE TITLE
[Bug] Org rendering issues

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#949]
Task | Org rendering issues
----------|----------
Description | When org is rendering with a lot of peers overlap occurs.  The managers also scroll under the name.  There are also no names of peers at the moment.

![Screen Shot 2018-12-31 at 11.29.49 AM.png](https://images.zenhubusercontent.com/575921babf93871ccd9c5898/b28ee824-29f2-4d76-88ef-247946b31a4a)
![Screen Shot 2018-12-31 at 11.29.56 AM.png](https://images.zenhubusercontent.com/575921babf93871ccd9c5898/cfbad095-af57-41b4-b2e0-c635d77e6890)

**Comment by pgobin** [comment]
Resolved in #977.
