### ISSUE TITLE
[Bug] Illegal key 503 when logging in as certain user

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#955]
Bug | Illegal key 503 when logging in as certain user
----------|----------
Bug Title | Illegal key 503 when logging in as certain user
Description | Login as Raymond Gong (username: Raymond Gong)`. Note "Illegal key" 503 from server
Username | Raymond Gong
ID | `CN=Raymond Gong,OU=Production,OU=Users,OU=Accounts,DC=clouddev,DC=corporate,DC=t-mobile,DC=com`

**Comment by PatrickLammers** [comment]
not repo
