### ISSUE TITLE
[Bug] Scrolling on individual requests page scrolls behind the title

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#964]
Bug | Scrolling on individual requests page scrolls behind the title
----------|----------
Expected behavior | Not do that
Actual behavior | Did that
Repro steps | Go to a profile with lots of pending requests and scroll
Severity | minor UI
![Screen Shot 2019-01-03 at 10.27.12 AM.png](https://images.zenhubusercontent.com/575921babf93871ccd9c5898/53c02f62-7310-446c-9288-93052c43e634)

**Comment by pgobin** [comment]
Addressed in #970
