### ISSUE TITLE
Refactor .env.example

### ISSUE THREAD

**Issue by jbobo** [hyperledger/sawtooth-next-directory#966]
Task | Add deployment variables to .env.example
----------|----------
Task Title | Add deployment variables to .env.example
Description | the deployment variables are missing from the example .env file. We should probably add descriptive comments to our example variables and reorganize it too for legibility.
Business Need (the why): | deployments are hard without these variables, and the .env file has grown quite a bit over the last few months.

**Comment by PatrickLammers** [comment]
seems more like a full blown story -- Tasks shouldn't get estimates.
