### ISSUE TITLE
[User Story] Slim Down Dockerfiles

### ISSUE THREAD

**Issue by jbobo** [hyperledger/sawtooth-next-directory#981]
[User Story] | Slim Down Dockerfiles
----------|----------
User Story Title | Slim Down Dockerfiles
T-shirt size: S(mall), M(edium), L(arge) | L 
User Story | [Value Statement] "Using a base cached Dockerfile for each image is straining available memory on dev/deployment machines."
Description | Slim down each Dockerfile to the bare essentials needed to run its microservice. Check overall and individual image size and boot time against the current images to prove that an improvement is being made.
Acceptance Criteria/Tests | Any changes to the Dockerfiles and Docker-compose.yaml result in smaller images and/or faster boot times.

**Comment by PatrickLammers** [comment]
Moving to S11 since Ned says there is work remaining on this story.  Maybe we could capture what that work is here so know?  Arbitrarily giving it a 1 point estimate -- Ned can revise @jbobo
