### ISSUE TITLE
[User Story] Migrate client base image to alpine

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#983]
User Story | Migrate client base image to alpine
----------|----------
Epic Title | (Epic NAME)
User Story Title | Migrate client base image to alpine
T-shirt size: S(mall), M(edium), L(arge) | S
Description | A short description 
Acceptance Criteria/Tests | The list of tests or criteria to be used to validate the story has been completed. May still need UAT or SIT / integration testing with other stories.

**Comment by pgobin** [comment]
> What benefit do we get out of doing this work?

The benefit in theory is a smaller footprint and better memory usage. This is a dupe of #1003.

**Comment by PatrickLammers** [comment]
Alpine gives us better compression...  but this is a very low priority story...
