### ISSUE TITLE
S2 [User Story] [UI Implementation] UI Scaffolding

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#99]
[User Story] | Multi-party approval, Approval configuration
----------|----------
Epic Title | Multi-party approval [#76](https://github.com/hyperledger/sawtooth-next-directory/issues/76)
User Story Title | UI Implementation - UI Scaffolding
T-shirt size | S
Story Points - Fibonacci (1,2,3,5,8,13) | 3
User Story | -
Description | The UI needs to be scaffolded out before development can proceed. This includes scaffolding an E2E/unit test harness.
Business Need (the why): | Dev will iterate much quicker than the legacy code currently in place
Details | React + Redux / Sagas is the combination that will be used moving forward. Scaffolding involves laying out the directory structure, adding Redux, tying it together with Sagas, hooking up the router, adding the bare minimum actions / reducers needed to verify a working app, and getting unit and E2E test infrastructure in place.
Additional User Story | linked
Acceptance Criteria/Tests | The list of tests or criteria to be used to validate the story has been completed. May still need UAT or SIT / integration testing with other stories.
Failure | if any, fold in negative tests
Definition of Done | Client and tests run locally                                                                                                   
UX/UI Details and/or mockups | if UI change, a mockup or description of what to change, attach image/file
Applications or Systems impacted | upstream/downstream applications/systems
Dependencies | non story dependencies
Assumptions | if any
Performance Considerations | Will the work performed as part of this story impact system performance. If there is potential for a performance hit, where would you expect it to manifest in the system.
Security Considerations | E.g., does this story involve working with Personal Identifying Information (PII)? Note any such security sensitive aspects.
QA Considerations | what might be hard to test or test setup criteria
Acrhitectural/System or Component Impacts | if we're adding something new or significantly changing architecture flag for architect review
Reverse Engineering Required | to document areas not known well by dev team
Questions/Clarifications | Create new issue (add label: question) in this repo and link to this issue

**Comment by pgobin** [comment]
[https://github.com/pgobin/sawtooth-next-directory/tree/scaffolding/ui](https://github.com/pgobin/sawtooth-next-directory/tree/scaffolding/ui)

**Comment by chimpuz** [comment]
@jiettu, @shrek-7 - Can you guys please take a look and contribute?
